openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: 'http://4.224.46.164:5055/'
paths:
  "/past_messages":
    post:
      summary: Get Past Messages
      operationId: get_past_messages_past_messages_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MessageFilter"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/MessageFilter"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    MessageFilter:
      properties:
        session_id:
          type: string
          title: Session Id
        start_date:
          type: string
          title: Start Date
        end_date:
          type: string
          title: End Date
        prompt:
          type: string
          title: Prompt
      type: object
      required:
      - session_id
      - start_date
      - end_date
      - prompt
      title: MessageFilter
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
