"""
Channel Metadata Catalog — Static registry of all 31 supported channels.

Provides per-channel: display name, auth method, setup fields, capabilities, icon, color.
Used by the setup wizard UI and the /api/social/channels/catalog endpoint.
"""

CHANNEL_CATALOG = {
    # ── Core Adapters ──────────────────────────────────────────
    'telegram': {
        'display_name': 'Telegram',
        'icon': 'telegram',
        'color': '#0088cc',
        'category': 'core',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'bot_token', 'label': 'Bot Token', 'type': 'password',
             'help': 'Create a bot via @BotFather and paste the token here.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': True, 'location': True, 'voice': True,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': False,
            'buttons': True, 'typing': True,
            'max_message_length': 4096,
        },
    },
    'discord': {
        'display_name': 'Discord',
        'icon': 'discord',
        'color': '#5865f2',
        'category': 'core',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'bot_token', 'label': 'Bot Token', 'type': 'password',
             'help': 'Create an application at discord.com/developers, add a Bot, and copy the token.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': True,
            'buttons': True, 'typing': True,
            'max_message_length': 2000,
        },
    },
    'slack': {
        'display_name': 'Slack',
        'icon': 'slack',
        'color': '#4a154b',
        'category': 'core',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'bot_token', 'label': 'Bot Token (xoxb-...)', 'type': 'password',
             'help': 'Create a Slack App, install it to your workspace, and copy the Bot User OAuth Token.'},
            {'key': 'signing_secret', 'label': 'Signing Secret', 'type': 'password',
             'help': 'Found in your Slack App settings under Basic Information.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': True,
            'buttons': True, 'typing': True,
            'max_message_length': 40000,
        },
    },
    'whatsapp': {
        'display_name': 'WhatsApp',
        'icon': 'whatsapp',
        'color': '#25d366',
        'category': 'core',
        'auth_method': 'credentials',
        'setup_fields': [
            {'key': 'api_url', 'label': 'WhatsApp Business API URL', 'type': 'text',
             'help': 'Your WhatsApp Business API endpoint.'},
            {'key': 'access_token', 'label': 'Access Token', 'type': 'password',
             'help': 'Permanent token from Meta Business dashboard.'},
            {'key': 'phone_number_id', 'label': 'Phone Number ID', 'type': 'text',
             'help': 'Your WhatsApp phone number ID from Meta.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': True, 'location': True, 'voice': True,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 4096,
        },
    },
    'signal': {
        'display_name': 'Signal',
        'icon': 'signal',
        'color': '#3a76f0',
        'category': 'core',
        'auth_method': 'credentials',
        'setup_fields': [
            {'key': 'signal_cli_path', 'label': 'signal-cli Path', 'type': 'text',
             'help': 'Path to signal-cli binary on the server.'},
            {'key': 'phone_number', 'label': 'Registered Phone Number', 'type': 'text',
             'help': 'Phone number registered with Signal (e.g. +1234567890).'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': True, 'location': False, 'voice': True,
            'reactions': True, 'message_edit': False, 'message_delete': True,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 6000,
        },
    },
    'imessage': {
        'display_name': 'iMessage',
        'icon': 'imessage',
        'color': '#34c759',
        'category': 'core',
        'auth_method': 'credentials',
        'setup_fields': [
            {'key': 'bridge_url', 'label': 'iMessage Bridge URL', 'type': 'text',
             'help': 'Requires a macOS machine running the iMessage bridge.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 20000,
        },
    },
    'google_chat': {
        'display_name': 'Google Chat',
        'icon': 'google_chat',
        'color': '#00ac47',
        'category': 'core',
        'auth_method': 'oauth2',
        'setup_fields': [
            {'key': 'client_id', 'label': 'OAuth Client ID', 'type': 'text',
             'help': 'From Google Cloud Console → APIs & Services → Credentials.'},
            {'key': 'client_secret', 'label': 'OAuth Client Secret', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': True, 'message_delete': True,
            'streaming': False, 'groups': True, 'threads': True,
            'buttons': True, 'typing': False,
            'max_message_length': 4096,
        },
    },
    'web': {
        'display_name': 'Web Chat',
        'icon': 'web',
        'color': '#6c63ff',
        'category': 'core',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'widget_key', 'label': 'Widget API Key', 'type': 'password',
             'help': 'Auto-generated. Embed the widget JS on your site.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': False, 'threads': False,
            'buttons': True, 'typing': True,
            'max_message_length': 10000,
        },
    },

    # ── Enterprise Adapters ────────────────────────────────────
    'teams': {
        'display_name': 'Microsoft Teams',
        'icon': 'teams',
        'color': '#6264a7',
        'category': 'enterprise',
        'auth_method': 'oauth2',
        'setup_fields': [
            {'key': 'app_id', 'label': 'Microsoft App ID', 'type': 'text',
             'help': 'From Azure Bot registration.'},
            {'key': 'app_password', 'label': 'App Password', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': True,
            'buttons': True, 'typing': True,
            'max_message_length': 28000,
        },
    },
    'mattermost': {
        'display_name': 'Mattermost',
        'icon': 'mattermost',
        'color': '#0058cc',
        'category': 'enterprise',
        'auth_method': 'websocket_token',
        'setup_fields': [
            {'key': 'server_url', 'label': 'Mattermost Server URL', 'type': 'text',
             'help': 'e.g. https://your-mattermost.example.com'},
            {'key': 'access_token', 'label': 'Personal Access Token', 'type': 'password',
             'help': 'Generate in Mattermost → Account Settings → Security.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': True,
            'buttons': True, 'typing': True,
            'max_message_length': 16383,
        },
    },
    'matrix': {
        'display_name': 'Matrix',
        'icon': 'matrix',
        'color': '#0dbd8b',
        'category': 'enterprise',
        'auth_method': 'websocket_token',
        'setup_fields': [
            {'key': 'homeserver_url', 'label': 'Homeserver URL', 'type': 'text',
             'help': 'e.g. https://matrix.org'},
            {'key': 'access_token', 'label': 'Access Token', 'type': 'password',
             'help': 'From Element → Settings → Help & About → Access Token.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': True, 'location': True, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': True,
            'buttons': False, 'typing': True,
            'max_message_length': 65536,
        },
    },
    'nextcloud': {
        'display_name': 'Nextcloud Talk',
        'icon': 'nextcloud',
        'color': '#0082c9',
        'category': 'enterprise',
        'auth_method': 'websocket_token',
        'setup_fields': [
            {'key': 'server_url', 'label': 'Nextcloud URL', 'type': 'text'},
            {'key': 'username', 'label': 'Username', 'type': 'text'},
            {'key': 'app_password', 'label': 'App Password', 'type': 'password',
             'help': 'Generate in Nextcloud → Settings → Security → App Passwords.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 32000,
        },
    },
    'rocketchat': {
        'display_name': 'Rocket.Chat',
        'icon': 'rocketchat',
        'color': '#f5455c',
        'category': 'enterprise',
        'auth_method': 'websocket_token',
        'setup_fields': [
            {'key': 'server_url', 'label': 'Rocket.Chat URL', 'type': 'text'},
            {'key': 'user_id', 'label': 'User ID', 'type': 'text'},
            {'key': 'auth_token', 'label': 'Auth Token', 'type': 'password',
             'help': 'Generate in Administration → Integrations or your profile.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': True,
            'buttons': True, 'typing': True,
            'max_message_length': 65536,
        },
    },

    # ── Social Adapters ────────────────────────────────────────
    'messenger': {
        'display_name': 'Facebook Messenger',
        'icon': 'messenger',
        'color': '#0084ff',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'page_access_token', 'label': 'Page Access Token', 'type': 'password',
             'help': 'From Meta Developer Portal → Your App → Messenger → Settings.'},
            {'key': 'app_secret', 'label': 'App Secret', 'type': 'password'},
            {'key': 'verify_token', 'label': 'Webhook Verify Token', 'type': 'text'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': True, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': False, 'threads': False,
            'buttons': True, 'typing': True,
            'max_message_length': 2000,
        },
    },
    'instagram': {
        'display_name': 'Instagram',
        'icon': 'instagram',
        'color': '#e4405f',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'page_access_token', 'label': 'Instagram Access Token', 'type': 'password',
             'help': 'Requires a connected Facebook Page with Instagram Professional account.'},
            {'key': 'app_secret', 'label': 'App Secret', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': False, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': False, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 1000,
        },
    },
    'twitter': {
        'display_name': 'Twitter / X',
        'icon': 'twitter',
        'color': '#1da1f2',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'bearer_token', 'label': 'API v2 Bearer Token', 'type': 'password',
             'help': 'From developer.twitter.com → Projects → Keys & Tokens.'},
            {'key': 'api_key', 'label': 'API Key', 'type': 'password'},
            {'key': 'api_secret', 'label': 'API Secret', 'type': 'password'},
            {'key': 'access_token', 'label': 'Access Token', 'type': 'password'},
            {'key': 'access_secret', 'label': 'Access Token Secret', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': False,
            'document': False, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': True,
            'streaming': False, 'groups': False, 'threads': False,
            'buttons': False, 'typing': False,
            'max_message_length': 10000,
        },
    },
    'line': {
        'display_name': 'LINE',
        'icon': 'line',
        'color': '#00b900',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'channel_access_token', 'label': 'Channel Access Token', 'type': 'password',
             'help': 'From LINE Developers Console → Messaging API → Channel access token.'},
            {'key': 'channel_secret', 'label': 'Channel Secret', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': False, 'sticker': True, 'location': True, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': True, 'typing': True,
            'max_message_length': 5000,
        },
    },
    'viber': {
        'display_name': 'Viber',
        'icon': 'viber',
        'color': '#665cac',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'auth_token', 'label': 'Bot Auth Token', 'type': 'password',
             'help': 'From partners.viber.com → Create Bot Account.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': False,
            'document': True, 'sticker': True, 'location': True, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': True, 'typing': True,
            'max_message_length': 7000,
        },
    },
    'wechat': {
        'display_name': 'WeChat',
        'icon': 'wechat',
        'color': '#07c160',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'app_id', 'label': 'Official Account App ID', 'type': 'text'},
            {'key': 'app_secret', 'label': 'App Secret', 'type': 'password'},
            {'key': 'token', 'label': 'Server Token', 'type': 'password',
             'help': 'The token you set in WeChat Official Account settings.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': False, 'sticker': False, 'location': True, 'voice': True,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': False, 'threads': False,
            'buttons': False, 'typing': False,
            'max_message_length': 2048,
        },
    },
    'zalo': {
        'display_name': 'Zalo',
        'icon': 'zalo',
        'color': '#0068ff',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'oa_access_token', 'label': 'Official Account Access Token', 'type': 'password',
             'help': 'From Zalo Developers → Your OA → Settings.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': True, 'sticker': True, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': False, 'threads': False,
            'buttons': True, 'typing': True,
            'max_message_length': 2000,
        },
    },
    'twitch': {
        'display_name': 'Twitch',
        'icon': 'twitch',
        'color': '#9146ff',
        'category': 'social',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'oauth_token', 'label': 'OAuth Token', 'type': 'password',
             'help': 'Generate at twitchapps.com/tmi or via Twitch Developer portal.'},
            {'key': 'channel_name', 'label': 'Channel Name', 'type': 'text'},
        ],
        'capabilities': {
            'text': True, 'image': False, 'video': False, 'audio': False,
            'document': False, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': True,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': False, 'typing': False,
            'max_message_length': 500,
        },
    },

    # ── Decentralized Adapters ─────────────────────────────────
    'nostr': {
        'display_name': 'Nostr',
        'icon': 'nostr',
        'color': '#8e30eb',
        'category': 'decentralized',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'private_key', 'label': 'Private Key (nsec)', 'type': 'password',
             'help': 'Your Nostr private key. Keep this safe!'},
            {'key': 'relays', 'label': 'Relay URLs (comma-separated)', 'type': 'text',
             'help': 'e.g. wss://relay.damus.io,wss://nos.lol'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': False, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': True, 'threads': True,
            'buttons': False, 'typing': False,
            'max_message_length': 65535,
        },
    },
    'tlon': {
        'display_name': 'Tlon (Urbit)',
        'icon': 'tlon',
        'color': '#1a1a2e',
        'category': 'decentralized',
        'auth_method': 'credentials',
        'setup_fields': [
            {'key': 'ship_url', 'label': 'Ship URL', 'type': 'text',
             'help': 'Your Urbit ship HTTP URL (e.g. http://localhost:8080).'},
            {'key': 'access_code', 'label': 'Access Code (+code)', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': False, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': True, 'message_delete': True,
            'streaming': False, 'groups': True, 'threads': True,
            'buttons': False, 'typing': False,
            'max_message_length': 65535,
        },
    },
    'openprose': {
        'display_name': 'OpenProse',
        'icon': 'openprose',
        'color': '#ff6b35',
        'category': 'decentralized',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'node_url', 'label': 'Node URL', 'type': 'text'},
            {'key': 'api_key', 'label': 'API Key', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': False, 'groups': True, 'threads': True,
            'buttons': False, 'typing': False,
            'max_message_length': 65535,
        },
    },

    # ── Bridge / User-Account Adapters ─────────────────────────
    'telegram_user': {
        'display_name': 'Telegram (User Account)',
        'icon': 'telegram',
        'color': '#0088cc',
        'category': 'bridge',
        'auth_method': 'qr_session',
        'setup_fields': [
            {'key': 'api_id', 'label': 'API ID', 'type': 'text',
             'help': 'From my.telegram.org → API Development Tools.'},
            {'key': 'api_hash', 'label': 'API Hash', 'type': 'password'},
            {'key': 'phone', 'label': 'Phone Number', 'type': 'text',
             'help': 'Your Telegram phone number for 2FA verification.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': True, 'location': True, 'voice': True,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 4096,
        },
    },
    'discord_user': {
        'display_name': 'Discord (User Account)',
        'icon': 'discord',
        'color': '#5865f2',
        'category': 'bridge',
        'auth_method': 'qr_session',
        'setup_fields': [
            {'key': 'user_token', 'label': 'User Token', 'type': 'password',
             'help': 'WARNING: Self-bots violate Discord ToS. Use at your own risk.'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': True, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': True, 'message_delete': True,
            'streaming': True, 'groups': True, 'threads': True,
            'buttons': False, 'typing': True,
            'max_message_length': 2000,
        },
    },
    'zalo_user': {
        'display_name': 'Zalo (User Account)',
        'icon': 'zalo',
        'color': '#0068ff',
        'category': 'bridge',
        'auth_method': 'phone_2fa',
        'setup_fields': [
            {'key': 'phone', 'label': 'Phone Number', 'type': 'text'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': True, 'sticker': True, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 2000,
        },
    },
    'bluebubbles': {
        'display_name': 'BlueBubbles (iMessage)',
        'icon': 'imessage',
        'color': '#34c759',
        'category': 'bridge',
        'auth_method': 'websocket_token',
        'setup_fields': [
            {'key': 'server_url', 'label': 'BlueBubbles Server URL', 'type': 'text',
             'help': 'Your BlueBubbles server address (requires macOS host).'},
            {'key': 'password', 'label': 'Server Password', 'type': 'password'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': True, 'audio': True,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': True, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': True, 'threads': False,
            'buttons': False, 'typing': True,
            'max_message_length': 20000,
        },
    },

    # ── Utility Adapters ───────────────────────────────────────
    'email': {
        'display_name': 'Email',
        'icon': 'email',
        'color': '#ea4335',
        'category': 'utility',
        'auth_method': 'credentials',
        'setup_fields': [
            {'key': 'imap_host', 'label': 'IMAP Server', 'type': 'text',
             'help': 'e.g. imap.gmail.com'},
            {'key': 'smtp_host', 'label': 'SMTP Server', 'type': 'text',
             'help': 'e.g. smtp.gmail.com'},
            {'key': 'email', 'label': 'Email Address', 'type': 'text'},
            {'key': 'password', 'label': 'Password / App Password', 'type': 'password',
             'help': 'Use an App Password for Gmail (2FA required).'},
        ],
        'capabilities': {
            'text': True, 'image': True, 'video': False, 'audio': False,
            'document': True, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': False, 'threads': True,
            'buttons': False, 'typing': False,
            'max_message_length': 100000,
        },
    },
    'voice': {
        'display_name': 'Voice (Twilio/Vonage)',
        'icon': 'voice',
        'color': '#f22f46',
        'category': 'utility',
        'auth_method': 'api_key',
        'setup_fields': [
            {'key': 'provider', 'label': 'Provider', 'type': 'select',
             'options': ['twilio', 'vonage'],
             'help': 'Choose your voice provider.'},
            {'key': 'account_sid', 'label': 'Account SID', 'type': 'text'},
            {'key': 'auth_token', 'label': 'Auth Token', 'type': 'password'},
            {'key': 'phone_number', 'label': 'Phone Number', 'type': 'text'},
        ],
        'capabilities': {
            'text': False, 'image': False, 'video': False, 'audio': True,
            'document': False, 'sticker': False, 'location': False, 'voice': True,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': False, 'threads': False,
            'buttons': False, 'typing': False,
            'max_message_length': 0,
        },
    },
    'hardware': {
        'display_name': 'Hardware (GPIO/ROS)',
        'icon': 'hardware',
        'color': '#607d8b',
        'category': 'utility',
        'auth_method': 'credentials',
        'setup_fields': [
            {'key': 'interface', 'label': 'Interface Type', 'type': 'select',
             'options': ['gpio', 'ros', 'serial'],
             'help': 'Choose the hardware interface.'},
            {'key': 'port', 'label': 'Port / Topic', 'type': 'text'},
        ],
        'capabilities': {
            'text': True, 'image': False, 'video': False, 'audio': False,
            'document': False, 'sticker': False, 'location': False, 'voice': False,
            'reactions': False, 'message_edit': False, 'message_delete': False,
            'streaming': False, 'groups': False, 'threads': False,
            'buttons': False, 'typing': False,
            'max_message_length': 1024,
        },
    },
}


def get_channel_metadata(channel_type: str):
    """Get metadata for a single channel, or None."""
    return CHANNEL_CATALOG.get(channel_type)


def list_all_channels():
    """Return the full catalog dict."""
    return CHANNEL_CATALOG


def get_channels_by_category(category: str):
    """Filter channels by category (core, enterprise, social, decentralized, bridge, utility)."""
    return {k: v for k, v in CHANNEL_CATALOG.items() if v.get('category') == category}


def get_channels_by_auth_method(method: str):
    """Filter channels by auth method."""
    return {k: v for k, v in CHANNEL_CATALOG.items() if v.get('auth_method') == method}
