// ════════════════════════════════════════════════════════════════════════════
// HART-comp — Milestone 6 (headline): zwlr_screencopy_v1 served against HART-comp's
// OWN output framebuffer, so `grim` captures HART-comp DIRECTLY.
// ════════════════════════════════════════════════════════════════════════════
//
// ── Why a hand-rolled protocol module (NOT a Smithay handler) ──
//   The pinned Smithay rev (47843391…) ships the NEWER `ext-image-copy-capture-v1`
//   (src/wayland/image_copy_capture/) but NO `zwlr_screencopy_v1` handler — and
//   `grim` (the de-facto wlroots screenshot tool, what M1-M5 used to capture the
//   HOST) speaks ONLY `zwlr_screencopy_manager_v1`/`zwlr_screencopy_frame_v1`. So
//   we advertise the wlr protocol directly: the bindings ARE in the tree
//   (`wayland_protocols_wlr::screencopy::v1::server`, the `server` feature of the
//   `wayland-protocols-wlr` crate Smithay re-exports), and we impl the RAW
//   `wayland_server::{GlobalDispatch, Dispatch}` traits on each backend's State (NOT
//   Smithay's `Dispatch2`, which is generated by `delegate_dispatch2!(State)` only for
//   the protocols Smithay owns — screencopy is not one, so there is no overlap and no
//   parallel path: this is the SINGLE screencopy implementation in the tree).
//
// ── ONE implementation, TWO backends (NATIVE_OS_PROGRAM 3.3, stream S5) ──
//   Until 2026-09-24 this file was `#![cfg(feature = "winit")]` and named
//   `crate::winit::State` directly, so the DRM backend never registered the global and
//   `grim` on the box said "compositor doesn't support wlr-screencopy-unstable-v1"
//   (docs/VERIFICATION.md row 23). The protocol bodies are now generic over
//   `ScreencopyState` (the backend hands over its queue; everything else comes from
//   `CompState`), and `delegate_screencopy!` stamps the raw `Dispatch` impls onto each
//   State the way Smithay's own delegate macros do. The read-back is generic over
//   `ExportMem`, so the winit path reads its bound window framebuffer and the DRM path
//   reads the scanout slot the `DrmCompositor` just rendered (udev.rs
//   `present_surfaces`), through the SAME `fill_one`.
//
// ── The wire flow (zwlr_screencopy_v1, grim's sequence) ──
//   1. client binds `zwlr_screencopy_manager_v1`, → `capture_output(frame, cursor, output)`
//   2. server creates the `zwlr_screencopy_frame_v1`, sends `buffer(Xrgb8888,w,h,stride)`
//      + (v3) `buffer_done`  — telling the client what to allocate.
//   3. client allocates an shm `wl_buffer` of that size/format, → `copy(buffer)`.
//   4. server reads back its framebuffer into that shm buffer, sends `flags(0)` then
//      `ready(tv_sec_hi, tv_sec_lo, tv_nsec)`.  On any failure → `failed()` (never
//      leave a client hanging — same fail-closed posture as the IPC).
//
//   Steps 1-3 run inline in the protocol handlers below; step 4 (the pixel read-back)
//   is DEFERRED to the render loop (`service_pending_screencopy` /
//   `service_pending_frames`), because the read-back needs the live renderer + the
//   just-painted framebuffer, which only exist inside the backend's render path. Each
//   `copy` enqueues a `PendingScreencopy`; the next paint drains the queue against the
//   real framebuffer. A backend with a frame-budget gate (the DRM path skips idle ticks)
//   is told a copy is waiting through `ScreencopyState::note_capture_requested`, so the
//   next tick paints instead of leaving grim to wait out the idle heartbeat.
//
// ── Kill-switch (constitutional, IPC_PROTOCOL.md §4.11 + §6.4) ──
//   When the human has cut `screen`, screencopy MUST refuse.  That authority lives
//   brain-side (a Python UDS); the compositor can NOT block on it per-frame.  Instead
//   the brain pushes the cut over the EXISTING IPC as `screen.kill {on:true}`, which
//   sets the backend's `capture_blocked` flag.  Every `copy`/`copy_with_damage` checks
//   it and immediately `failed()`s while set — the no-native-capture invariant enforced
//   at the compositor with ZERO per-frame IPC — and a cut ALSO fails every frame already
//   queued (`fail_pending`), so a capture requested a tick before the cut never reads a
//   frame painted before the black surface. Nothing in this protocol can flip the flag:
//   §6.4's "no verb re-enables a cut sense" holds by construction, since the only writer
//   is `CompState::set_capture_blocked`, driven by the brain's edge.  Until the Phase-7
//   portal lands, this is the governed capture path and honours the same gate.

#![cfg(any(feature = "winit", feature = "smithay"))]

use std::sync::atomic::{AtomicBool, Ordering};

use smithay::backend::allocator::Fourcc;
use smithay::backend::renderer::{ExportMem, RendererSuper};
use smithay::reexports::wayland_protocols_wlr::screencopy::v1::server::{
    zwlr_screencopy_frame_v1::{self, ZwlrScreencopyFrameV1},
    zwlr_screencopy_manager_v1::{self, ZwlrScreencopyManagerV1},
};
use smithay::reexports::wayland_server::{
    protocol::{wl_buffer::WlBuffer, wl_shm},
    Client, DataInit, Dispatch, DisplayHandle, GlobalDispatch, New, Resource,
};
use smithay::utils::{Buffer as BufferCoord, Physical, Rectangle, Size, Transform};
use smithay::wayland::shm::{shm_format_to_fourcc, with_buffer_contents_mut, BufferData};
use tracing::{debug, info, warn};

use crate::comp_core::{self, CompState};

/// We capture in Xrgb8888 — the mandatory shm format every wlr client (grim,
/// wf-recorder) understands, and the format both renderers read back cleanly. Argb
/// would advertise an alpha grim then has to flatten; Xrgb is the honest "opaque
/// desktop" format and what wlroots compositors advertise first.
const CAPTURE_FOURCC: Fourcc = Fourcc::Xrgb8888;

/// The protocol version advertised by both backends. 3 is the `buffer_done` level grim
/// uses; one constant so the two `create_global` calls cannot drift.
pub const SCREENCOPY_VERSION: u32 = 3;

/// What a backend must hand this module beyond `CompState`: the queue of copies waiting
/// for a paint. The winit and DRM States each own one; the protocol bodies below never
/// name either State.
pub trait ScreencopyState: CompState + 'static {
    fn pending_screencopy_mut(&mut self) -> &mut Vec<PendingScreencopy>;

    /// A copy was queued. A backend whose render tick skips idle frames (the DRM path's
    /// #137 gate) marks itself damaged here, so the read-back happens on the next tick
    /// rather than after the 200 ms idle heartbeat. The winit loop paints every
    /// iteration, so its default is a no-op.
    fn note_capture_requested(&mut self) {}
}

#[cfg(feature = "winit")]
impl ScreencopyState for crate::winit::State {
    fn pending_screencopy_mut(&mut self) -> &mut Vec<PendingScreencopy> {
        &mut self.pending_screencopy
    }
}

/// Per-frame state (the `zwlr_screencopy_frame_v1` user-data). Holds the region the
/// client asked to capture (validated against the output in `capture_output*`) and a
/// one-shot `used` guard: the protocol says a frame object may be `copy`'d EXACTLY
/// once (`already_used` error otherwise). The raw `Dispatch::request` gives only
/// `&data`, hence interior mutability.
pub struct ScreencopyFrameData {
    /// The capture region in OUTPUT-buffer coordinates (physical px, origin top-left).
    pub region: Rectangle<i32, BufferCoord>,
    /// One-shot guard: a frame object may be `copy`'d EXACTLY once (the protocol's
    /// `already_used` error otherwise). `AtomicBool` (not `Cell`) because wayland-server
    /// requires resource user-data to be `Send + Sync`, and `Cell` is `!Sync`.
    pub used: AtomicBool,
}

/// A `copy`-requested frame awaiting the next paint to be filled from the real
/// framebuffer. Queued on the backend State; drained by the render loop. Owns the frame
/// resource (so it can send `ready`/`failed`) + the client's destination buffer + the
/// region.
pub struct PendingScreencopy {
    pub frame: ZwlrScreencopyFrameV1,
    pub buffer: WlBuffer,
    pub region: Rectangle<i32, BufferCoord>,
    pub with_damage: bool,
}

/// What `copy` does with a request, decided in this order. PURE so the gate is
/// unit-tested on both feature builds without a live State or a client buffer.
///
/// The kill-switch is checked FIRST and wins over everything: a client whose capture is
/// cut learns nothing about its buffer, and its frame is not even marked used, because
/// nothing about that frame has been evaluated. A re-used frame is a protocol error (the
/// spec's `already_used`), which is fatal to the client; a buffer that does not match the
/// advertised format or size is `failed()` (the client may retry with a right one).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CopyVerdict {
    /// The human has cut `screen`: `failed()`, no read-back, nothing learned.
    Blocked,
    /// The frame object was already copied: `already_used` protocol error.
    AlreadyUsed,
    /// The destination is not an shm buffer of the advertised size/format: `failed()`.
    BadBuffer,
    /// Enqueue; the next paint fills it.
    Queue,
}

pub fn copy_admission(capture_blocked: bool, already_used: bool, buffer_matches: bool) -> CopyVerdict {
    if capture_blocked {
        CopyVerdict::Blocked
    } else if already_used {
        CopyVerdict::AlreadyUsed
    } else if !buffer_matches {
        CopyVerdict::BadBuffer
    } else {
        CopyVerdict::Queue
    }
}

/// The shm formats a client may hand `copy`. We advertise Xrgb8888; Argb8888 is the same
/// bytes with an alpha channel the read-back writes as opaque, and grim allocates either.
pub fn client_format_accepted(format: wl_shm::Format) -> bool {
    matches!(format, wl_shm::Format::Xrgb8888 | wl_shm::Format::Argb8888)
}

// ════════════════════════════════════════════════════════════════════════════
// The protocol bodies, generic over the backend State.
// ════════════════════════════════════════════════════════════════════════════

/// The manager's two capture requests. `CaptureOutput` is the whole output;
/// `CaptureOutputRegion` is clamped to it so a client can never read outside the
/// framebuffer (the ExportMem contract rejects an out-of-bounds region — we clamp rather
/// than fail so a slightly-oversized region still yields a sane capture). HART-comp has
/// exactly ONE output on either backend, so the `output` argument is not consulted.
pub fn manager_request<S>(
    state: &mut S,
    request: zwlr_screencopy_manager_v1::Request,
    data_init: &mut DataInit<'_, S>,
) where
    S: ScreencopyState + Dispatch<ZwlrScreencopyFrameV1, ScreencopyFrameData>,
{
    match request {
        zwlr_screencopy_manager_v1::Request::CaptureOutput {
            frame,
            overlay_cursor: _,
            output: _,
        } => {
            let size = comp_core::output_physical_size(state);
            let region = Rectangle::from_size((size.w, size.h).into());
            init_frame(frame, region, data_init);
        }
        zwlr_screencopy_manager_v1::Request::CaptureOutputRegion {
            frame,
            overlay_cursor: _,
            output: _,
            x,
            y,
            width,
            height,
        } => {
            let out = comp_core::output_physical_size(state);
            let region = comp_core::clamp_region(x, y, width, height, out.w, out.h);
            init_frame(frame, region, data_init);
        }
        zwlr_screencopy_manager_v1::Request::Destroy => {}
        _ => {}
    }
}

/// Create the frame object + tell the client what buffer to allocate (the `buffer`
/// event = format/size/stride, then v3 `buffer_done`). Xrgb8888, 4 bytes/px, stride =
/// width*4. The frame's user-data carries the region so `copy` knows what to read.
fn init_frame<S>(
    frame: New<ZwlrScreencopyFrameV1>,
    region: Rectangle<i32, BufferCoord>,
    data_init: &mut DataInit<'_, S>,
) where
    S: Dispatch<ZwlrScreencopyFrameV1, ScreencopyFrameData>,
{
    let data = ScreencopyFrameData {
        region,
        used: AtomicBool::new(false),
    };
    let frame = data_init.init(frame, data);
    let w = region.size.w as u32;
    let h = region.size.h as u32;
    let stride = w * 4; // Xrgb8888 = 4 bytes per pixel.
    // `buffer` advertises the shm format + dimensions the client must allocate.
    frame.buffer(wl_shm::Format::Xrgb8888, w, h, stride);
    // v3: `buffer_done` says "no more buffer/linux_dmabuf events; pick one + copy".
    if frame.version() >= 3 {
        frame.buffer_done();
    }
}

/// The frame object's requests: `copy` / `copy_with_damage` enqueue the read-back; the
/// render loop fills it. `destroy` is the destructor.
pub fn frame_request<S: ScreencopyState>(
    state: &mut S,
    resource: &ZwlrScreencopyFrameV1,
    request: zwlr_screencopy_frame_v1::Request,
    data: &ScreencopyFrameData,
) {
    match request {
        zwlr_screencopy_frame_v1::Request::Copy { buffer } => {
            queue_copy(state, resource, data, buffer, false);
        }
        zwlr_screencopy_frame_v1::Request::CopyWithDamage { buffer } => {
            queue_copy(state, resource, data, buffer, true);
        }
        zwlr_screencopy_frame_v1::Request::Destroy => {}
        _ => {}
    }
}

/// Validate the client buffer + enqueue the read-back (or `failed()` immediately on a
/// bad buffer / re-use / killswitch). The actual pixel copy happens on the next paint —
/// this only checks + queues. The decision order is `copy_admission`'s.
fn queue_copy<S: ScreencopyState>(
    state: &mut S,
    frame: &ZwlrScreencopyFrameV1,
    data: &ScreencopyFrameData,
    buffer: WlBuffer,
    with_damage: bool,
) {
    let blocked = state.capture_blocked();
    // Not marked used while blocked: the frame was never evaluated.
    let already_used = !blocked && data.used.swap(true, Ordering::SeqCst);
    // The destination MUST be an shm buffer of the advertised size/format. A non-shm
    // (e.g. dmabuf) buffer or a size mismatch fails the copy (we advertised an shm
    // `buffer` event, so a well-behaved client always sends shm). Only read when the
    // two gates above passed, so a cut sense evaluates nothing about the client.
    let expected_w = data.region.size.w;
    let expected_h = data.region.size.h;
    let buffer_matches = !blocked
        && !already_used
        && with_buffer_contents_mut(&buffer, |_ptr, _len, bd: BufferData| {
            client_format_accepted(bd.format) && bd.width == expected_w && bd.height == expected_h
        })
        .unwrap_or_else(|err| {
            debug!(?err, "screencopy: with_buffer_contents_mut could not read the client shm buffer");
            false
        });

    match copy_admission(blocked, already_used, buffer_matches) {
        CopyVerdict::Blocked => {
            info!("screencopy: capture blocked by the screen kill-switch; failing the frame");
            frame.failed();
        }
        CopyVerdict::AlreadyUsed => {
            frame.post_error(
                zwlr_screencopy_frame_v1::Error::AlreadyUsed,
                "screencopy frame already used",
            );
        }
        CopyVerdict::BadBuffer => {
            warn!(
                expected_w,
                expected_h, "screencopy: client buffer is not a matching shm buffer; failing"
            );
            frame.failed();
        }
        CopyVerdict::Queue => {
            state.pending_screencopy_mut().push(PendingScreencopy {
                frame: frame.clone(),
                buffer,
                region: data.region,
                with_damage,
            });
            state.note_capture_requested();
        }
    }
}

/// The kill-switch's queue half: fail every frame already waiting for a paint, so a
/// capture queued a tick before the cut never reads a frame painted before the black
/// surface. Called by each backend's `set_capture_blocked` override when `on` is true.
pub fn fail_pending<S: ScreencopyState>(state: &mut S) {
    fail_pending_frames(state.pending_screencopy_mut());
}

/// `fail_pending` on a queue the caller already holds (the DRM render tick has the
/// queue out of its State while it presents).
pub fn fail_pending_frames(pending: &mut Vec<PendingScreencopy>) {
    for p in pending.drain(..) {
        p.frame.failed();
    }
}

// ════════════════════════════════════════════════════════════════════════════
// The delegate macro: the raw `GlobalDispatch` / `Dispatch` impls for one State, each a
// one-line forward to the generic bodies above. Invoked once per backend below, the way
// Smithay's own `delegate_*!` macros are; the State never names the protocol types.
// ════════════════════════════════════════════════════════════════════════════

macro_rules! delegate_screencopy {
    ($state:ty) => {
        impl GlobalDispatch<ZwlrScreencopyManagerV1, ()> for $state {
            fn bind(
                _state: &mut $state,
                _handle: &DisplayHandle,
                _client: &Client,
                resource: New<ZwlrScreencopyManagerV1>,
                _global_data: &(),
                data_init: &mut DataInit<'_, $state>,
            ) {
                data_init.init(resource, ());
            }
        }

        impl Dispatch<ZwlrScreencopyManagerV1, ()> for $state {
            fn request(
                state: &mut $state,
                _client: &Client,
                _resource: &ZwlrScreencopyManagerV1,
                request: zwlr_screencopy_manager_v1::Request,
                _data: &(),
                _dhandle: &DisplayHandle,
                data_init: &mut DataInit<'_, $state>,
            ) {
                manager_request(state, request, data_init);
            }
        }

        impl Dispatch<ZwlrScreencopyFrameV1, ScreencopyFrameData> for $state {
            fn request(
                state: &mut $state,
                _client: &Client,
                resource: &ZwlrScreencopyFrameV1,
                request: zwlr_screencopy_frame_v1::Request,
                data: &ScreencopyFrameData,
                _dhandle: &DisplayHandle,
                _data_init: &mut DataInit<'_, $state>,
            ) {
                frame_request(state, resource, request, data);
            }
        }
    };
}

#[cfg(feature = "winit")]
delegate_screencopy!(crate::winit::State);

#[cfg(feature = "smithay")]
delegate_screencopy!(crate::wayland::State);

// ════════════════════════════════════════════════════════════════════════════
// The render-loop hook — drain queued frames against the JUST-PAINTED framebuffer.
// winit calls it after `frame.finish()` on its bound window framebuffer; the DRM tick
// calls it (through `service_pending_frames`) on the scanout slot the DrmCompositor just
// rendered, bound through `Bind<Dmabuf>`. Both read through `ExportMem`, so it is one
// read-back for both renderers.
// ════════════════════════════════════════════════════════════════════════════

/// Service every queued screencopy frame on `state`: read back the framebuffer region
/// into the client's shm buffer, then send `flags` + `ready` (or `failed`). Drains the
/// queue (every frame is one-shot). `output_transform` is the output's render transform
/// (Flipped180 on winit, Normal on DRM) so the captured pixels match what the user sees
/// upright.
pub fn service_pending_screencopy<S, R>(
    state: &mut S,
    renderer: &mut R,
    framebuffer: &<R as RendererSuper>::Framebuffer<'_>,
    output_size: Size<i32, Physical>,
    output_transform: Transform,
) where
    S: ScreencopyState,
    R: ExportMem,
{
    let mut pending = std::mem::take(state.pending_screencopy_mut());
    service_pending_frames(&mut pending, renderer, framebuffer, output_size, output_transform);
}

/// `service_pending_screencopy` on a queue the caller holds. Empties it.
///
/// The read-back uses `ExportMem::copy_framebuffer` (a glReadPixels on the Gles path, a
/// pixman blit on the floor) → `map_texture` (the CPU-side bytes) → memcpy into the shm
/// map. The captured frame is EXACTLY the displayed frame (cursor + effects + killswitch
/// surface all painted into `framebuffer` already), which is the whole point of
/// capturing HART-comp's own output rather than a host re-composite.
pub fn service_pending_frames<R: ExportMem>(
    pending: &mut Vec<PendingScreencopy>,
    renderer: &mut R,
    framebuffer: &<R as RendererSuper>::Framebuffer<'_>,
    output_size: Size<i32, Physical>,
    output_transform: Transform,
) {
    if pending.is_empty() {
        return;
    }
    for p in pending.drain(..) {
        match fill_one(renderer, framebuffer, &p, output_size, output_transform) {
            Ok(()) => {}
            Err(e) => {
                warn!(error = %e, "screencopy: read-back failed; failing the frame");
                p.frame.failed();
            }
        }
    }
}

/// Read back ONE frame's region + copy it into the client buffer + signal ready.
/// Separated so the `?` early-returns map to a single `failed()` at the call site.
fn fill_one<R: ExportMem>(
    renderer: &mut R,
    framebuffer: &<R as RendererSuper>::Framebuffer<'_>,
    p: &PendingScreencopy,
    output_size: Size<i32, Physical>,
    output_transform: Transform,
) -> Result<(), String> {
    // The framebuffer is stored in the output's RENDER transform (Flipped180 on winit,
    // Normal on DRM). `copy_framebuffer` reads the RAW framebuffer, so to hand the client
    // an upright image we map the logical capture region through the transform to the
    // physical framebuffer rectangle. Flipped180 is a Y-axis flip (x preserved): the
    // mapped rect for a full-output capture is the same rect; for a sub-region only the
    // y origin moves (`area.h - y - height`). Normal is the identity.
    // `Transform::transform_rect_in` does exactly this.
    let fb_region = comp_core::transform_region(p.region, output_size, output_transform);

    // Read back the framebuffer pixels (Xrgb8888) for the region.
    let mapping = renderer
        .copy_framebuffer(framebuffer, fb_region, CAPTURE_FOURCC)
        .map_err(|e| format!("copy_framebuffer: {e:?}"))?;
    let pixels: &[u8] = renderer
        .map_texture(&mapping)
        .map_err(|e| format!("map_texture: {e:?}"))?;

    let src_w = p.region.size.w as usize;
    let src_h = p.region.size.h as usize;
    let src_stride = src_w * 4;
    if pixels.len() < src_stride * src_h {
        return Err(format!(
            "read-back too small: {} < {}",
            pixels.len(),
            src_stride * src_h
        ));
    }

    // Copy into the client's shm buffer row-by-row (honour the client's stride; it may
    // differ from ours if the client over-allocated). The region was already mapped
    // through the transform above and we report no y_invert flag, so a straight row
    // copy is correct here.
    let copied = with_buffer_contents_mut(&p.buffer, |ptr, len, bd: BufferData| {
        let dst_stride = bd.stride as usize;
        let dst_off = bd.offset as usize;
        let rows = src_h.min(bd.height as usize);
        let row_bytes = src_stride.min(dst_stride);
        // Map the shm-format byte order: our read-back is Fourcc::Xrgb8888 (little-
        // endian BGRX in memory, matching wl_shm Xrgb8888), so a direct row copy lands
        // the right bytes for an Xrgb/Argb client buffer.
        // The ONLY unsafe in this crate (see Cargo.toml [lints.rust]): Smithay hands
        // the shm mapping as a raw `*mut u8` + `len`, with no safe write helper for the
        // wlr-screencopy copy at this pinned rev. We build a checked `&mut [u8]` over the
        // mapping ONCE and write rows through safe slicing thereafter.
        // SAFETY: `with_buffer_contents_mut`'s contract guarantees `ptr` is a valid,
        // uniquely-borrowed, writable mapping of exactly `len` bytes for the duration of
        // this closure (it holds the pool lock). `u8` has no alignment/init requirements.
        // No other reference to this mapping exists while the closure runs.
        #[allow(unsafe_code)]
        let dst: &mut [u8] = unsafe { std::slice::from_raw_parts_mut(ptr, len) };
        for row in 0..rows {
            let s = row * src_stride;
            let d = dst_off + row * dst_stride;
            if d + row_bytes > len || s + row_bytes > pixels.len() {
                break;
            }
            dst[d..d + row_bytes].copy_from_slice(&pixels[s..s + row_bytes]);
        }
        rows
    })
    .map_err(|e| format!("with_buffer_contents_mut: {e:?}"))?;

    if copied == 0 {
        return Err("copied 0 rows".into());
    }

    // Tell the client the result is upright (no y-invert; we already corrected the
    // transform), then signal completion with a presentation timestamp.
    p.frame.flags(zwlr_screencopy_frame_v1::Flags::empty());
    if p.with_damage && p.frame.version() >= 2 {
        // We always have full damage on the single output.
        p.frame.damage(
            0,
            0,
            p.region.size.w as u32,
            p.region.size.h as u32,
        );
    }
    let (sec, nsec) = comp_core::now_secs_nsecs();
    let tv_sec_hi = (sec >> 32) as u32;
    let tv_sec_lo = (sec & 0xFFFF_FFFF) as u32;
    p.frame.ready(tv_sec_hi, tv_sec_lo, nsec);
    Ok(())
}

// The PURE region/time helpers — `clamp_region`, `transform_region`, `now_secs_nsecs` —
// live in comp_core.rs (hoisted there while this file was winit-only, so the smithay
// doCheck could exercise them). The handlers above CALL them via `comp_core::` (one
// source of truth, no parallel path); their unit floor stays in comp_core.rs.

/// Whether a wl_shm format has a Fourcc the read-back can target.
#[allow(unused)]
pub(crate) fn shm_supported(format: wl_shm::Format) -> bool {
    shm_format_to_fourcc(format).is_some()
}

// ════════════════════════════════════════════════════════════════════════════
// The gate + format floor. `copy_admission` is the whole `copy` decision and
// `client_format_accepted` the whole format set, both pure, so the kill-switch's
// precedence and the accepted formats are pinned on BOTH feature builds (this file now
// compiles under `--features smithay`, which is what hart-comp.nix's doCheck runs). The
// live half (a real State + client buffer) is the smoke_e2e killswitch round-trip and
// `grim` on the box.
// ════════════════════════════════════════════════════════════════════════════
#[cfg(test)]
mod tests {
    use super::*;

    // ── format invariants ──

    #[test]
    fn capture_fourcc_is_the_mandatory_opaque_format() {
        assert_eq!(CAPTURE_FOURCC, Fourcc::Xrgb8888, "we advertise the opaque Xrgb floor");
        // The `buffer` event names the shm twin of the same format, so a client that
        // allocates exactly what it was told always passes the format gate.
        assert_eq!(shm_format_to_fourcc(wl_shm::Format::Xrgb8888), Some(CAPTURE_FOURCC));
    }

    #[test]
    fn shm_supported_accepts_the_wlr_capture_formats() {
        // grim/wf-recorder always allocate Xrgb8888 or Argb8888 — both must map to a
        // Fourcc (the read-back copies straight into either).
        assert!(shm_supported(wl_shm::Format::Xrgb8888));
        assert!(shm_supported(wl_shm::Format::Argb8888));
    }

    #[test]
    fn the_client_format_set_is_exactly_the_two_8888_shm_formats() {
        assert!(client_format_accepted(wl_shm::Format::Xrgb8888));
        assert!(client_format_accepted(wl_shm::Format::Argb8888));
        // A 16-bit or 10-bit buffer would be row-copied as if it were 4 bytes a pixel,
        // which is garbage for the client and a possible over-read for us.
        assert!(!client_format_accepted(wl_shm::Format::Rgb565));
        assert!(!client_format_accepted(wl_shm::Format::Xrgb2101010));
        assert!(!client_format_accepted(wl_shm::Format::Abgr8888));
    }

    // ── the kill-switch gate (IPC_PROTOCOL 4.11 point 3, 6.4) ──

    #[test]
    fn a_cut_screen_refuses_every_copy_before_anything_else_is_evaluated() {
        // Blocked wins over a fresh, valid request...
        assert_eq!(copy_admission(true, false, true), CopyVerdict::Blocked);
        // ...and over a re-used frame and a bad buffer: a cut sense learns nothing about
        // the request and reports nothing but `failed`.
        assert_eq!(copy_admission(true, true, true), CopyVerdict::Blocked);
        assert_eq!(copy_admission(true, false, false), CopyVerdict::Blocked);
        assert_eq!(copy_admission(true, true, false), CopyVerdict::Blocked);
    }

    #[test]
    fn an_open_screen_queues_a_valid_copy_and_refuses_the_two_protocol_faults() {
        assert_eq!(copy_admission(false, false, true), CopyVerdict::Queue);
        // A second `copy` on the same frame object is the spec's `already_used`.
        assert_eq!(copy_admission(false, true, true), CopyVerdict::AlreadyUsed);
        assert_eq!(copy_admission(false, true, false), CopyVerdict::AlreadyUsed);
        // A buffer that is not what `buffer` advertised fails the frame.
        assert_eq!(copy_admission(false, false, false), CopyVerdict::BadBuffer);
    }

    #[test]
    fn restoring_the_screen_admits_copies_again_and_nothing_here_can_restore_it() {
        // The gate is a pure function of the flag: the only thing that changes the
        // verdict is the flag the brain drives through `screen.kill`. There is no
        // argument a client could pass that turns Blocked into Queue.
        for used in [false, true] {
            for ok in [false, true] {
                assert_eq!(copy_admission(true, used, ok), CopyVerdict::Blocked);
            }
        }
        assert_eq!(copy_admission(false, false, true), CopyVerdict::Queue);
    }

    // ── the DRM transform: Normal is the identity, so a full-output capture on the box
    //    reads the scanout slot 1:1 (winit's Flipped180 is covered in comp_core.rs) ──

    #[test]
    fn a_normal_output_transform_maps_every_region_to_itself() {
        let out: Size<i32, Physical> = (1600, 900).into();
        for (x, y, w, h) in [(0, 0, 1600, 900), (10, 20, 300, 200), (1500, 800, 100, 100)] {
            let r: Rectangle<i32, BufferCoord> = Rectangle::new((x, y).into(), (w, h).into());
            assert_eq!(comp_core::transform_region(r, out, Transform::Normal), r);
        }
    }

    #[test]
    fn both_backends_advertise_the_same_protocol_version() {
        // grim needs `buffer_done` (v3). Pinned so the DRM global cannot regress to a
        // version whose clients wait forever for an event we never send.
        assert_eq!(SCREENCOPY_VERSION, 3);
    }
}
