// ════════════════════════════════════════════════════════════════════════════
// HART-comp — Milestone 6 (headline): zwlr_screencopy_v1 served against HART-comp's
// OWN output framebuffer, so `grim` captures HART-comp DIRECTLY.
// ════════════════════════════════════════════════════════════════════════════
//
// ── Why a hand-rolled protocol module (NOT a Smithay handler) ──
//   The pinned Smithay rev (47843391…) ships the NEWER `ext-image-copy-capture-v1`
//   (src/wayland/image_copy_capture/) but NO `zwlr_screencopy_v1` handler — and
//   `grim` (the de-facto wlroots screenshot tool, what M1-M5 used to capture the
//   HOST) speaks ONLY `zwlr_screencopy_manager_v1`/`zwlr_screencopy_frame_v1`. So
//   we advertise the wlr protocol directly: the bindings ARE in the tree
//   (`wayland_protocols_wlr::screencopy::v1::server`, the `server` feature of the
//   `wayland-protocols-wlr` crate Smithay re-exports), and we impl the RAW
//   `wayland_server::{GlobalDispatch, Dispatch}` traits on `State` (NOT Smithay's
//   `Dispatch2`, which is generated by `delegate_dispatch2!(State)` only for the
//   protocols Smithay owns — screencopy is not one, so there is no overlap and no
//   parallel path: this is the SINGLE screencopy implementation in the tree).
//
// ── Why this is the clean capture path (the M6 ordering rationale) ──
//   Through M5, `grim` had to capture the SWAY HOST that composites HART-comp
//   full-screen (HART-comp advertised no screencopy). That re-composite path can
//   NOT prove HART-comp's own cursor / fade animations / the killswitch black
//   surface — they are HART-comp-internal and the host only sees the final pixels
//   it was handed. Servicing screencopy against HART-comp's OWN framebuffer lets
//   `WAYLAND_DISPLAY=<hart socket> grim x.png` read back exactly what HART-comp
//   painted (cursor + effects included), so screencopy is built FIRST and the other
//   three M6 features are verified THROUGH it.
//
// ── The wire flow (zwlr_screencopy_v1, grim's sequence) ──
//   1. client binds `zwlr_screencopy_manager_v1`, → `capture_output(frame, cursor, output)`
//   2. server creates the `zwlr_screencopy_frame_v1`, sends `buffer(Xrgb8888,w,h,stride)`
//      + (v3) `buffer_done`  — telling the client what to allocate.
//   3. client allocates an shm `wl_buffer` of that size/format, → `copy(buffer)`.
//   4. server reads back its framebuffer into that shm buffer, sends `flags(0)` then
//      `ready(tv_sec_hi, tv_sec_lo, tv_nsec)`.  On any failure → `failed()` (never
//      leave a client hanging — same fail-closed posture as the IPC).
//
//   Steps 1-3 run inline in the protocol handlers below; step 4 (the pixel read-back)
//   is DEFERRED to the render loop (`service_pending_screencopy`), because the
//   read-back needs the live `GlesRenderer` + the just-painted `Framebuffer`, which
//   only exist inside winit.rs's render closure.  Each `copy` enqueues a
//   `PendingScreencopy`; the next paint drains the queue against the real framebuffer.
//
// ── Kill-switch (constitutional, IPC_PROTOCOL.md §6.4 + killswitch_plan) ──
//   When the human has cut `screen`, screencopy MUST refuse.  That authority lives
//   brain-side (a Python UDS); the compositor can NOT block on it per-frame.  Instead
//   the brain pushes the cut over the EXISTING IPC as `screen.kill {on:true}`, which
//   sets `State.capture_blocked`.  Every `copy`/`copy_with_damage` checks it and
//   immediately `failed()`s while set — the no-native-capture invariant enforced at
//   the compositor with ZERO per-frame IPC.  Until the Phase-7 portal lands, this is
//   the governed capture path and honours the same gate.

#![cfg(feature = "winit")]

use std::sync::atomic::{AtomicBool, Ordering};

use smithay::backend::allocator::Fourcc;
use smithay::backend::renderer::gles::{GlesRenderer, GlesTarget};
use smithay::backend::renderer::ExportMem;
use smithay::reexports::wayland_protocols_wlr::screencopy::v1::server::{
    zwlr_screencopy_frame_v1::{self, ZwlrScreencopyFrameV1},
    zwlr_screencopy_manager_v1::{self, ZwlrScreencopyManagerV1},
};
use smithay::reexports::wayland_server::{
    protocol::{wl_buffer::WlBuffer, wl_shm},
    Client, DataInit, Dispatch, DisplayHandle, GlobalDispatch, New, Resource,
};
use smithay::utils::{Buffer as BufferCoord, Physical, Rectangle, Size, Transform};
use smithay::wayland::shm::{shm_format_to_fourcc, with_buffer_contents_mut, BufferData};
use tracing::{debug, info, warn};

use crate::comp_core;
use crate::winit::State;

/// We capture in Xrgb8888 — the mandatory shm format every wlr client (grim,
/// wf-recorder) understands, and the format the winit GlesRenderer reads back
/// cleanly. Argb would advertise an alpha grim then has to flatten; Xrgb is the
/// honest "opaque desktop" format and what wlroots compositors advertise first.
const CAPTURE_FOURCC: Fourcc = Fourcc::Xrgb8888;

/// Per-frame state (the `zwlr_screencopy_frame_v1` user-data). Holds the region the
/// client asked to capture (validated against the output in `capture_output*`) and a
/// one-shot `used` guard: the protocol says a frame object may be `copy`'d EXACTLY
/// once (`already_used` error otherwise). `Cell` for interior mutability — the raw
/// `Dispatch::request` gives only `&data`.
pub struct ScreencopyFrameData {
    /// The capture region in OUTPUT-buffer coordinates (physical px, origin top-left).
    pub region: Rectangle<i32, BufferCoord>,
    /// One-shot guard: a frame object may be `copy`'d EXACTLY once (the protocol's
    /// `already_used` error otherwise). `AtomicBool` (not `Cell`) because wayland-server
    /// requires resource user-data to be `Send + Sync`, and `Cell` is `!Sync`.
    pub used: AtomicBool,
}

/// A `copy`-requested frame awaiting the next paint to be filled from the real
/// framebuffer. Queued in `State.pending_screencopy`; drained by
/// `service_pending_screencopy` in the render loop. Owns the frame resource (so it can
/// send `ready`/`failed`) + the client's destination buffer + the region.
pub struct PendingScreencopy {
    pub frame: ZwlrScreencopyFrameV1,
    pub buffer: WlBuffer,
    pub region: Rectangle<i32, BufferCoord>,
    pub with_damage: bool,
}

// ════════════════════════════════════════════════════════════════════════════
// The manager global — `bind` + the two capture requests.
// ════════════════════════════════════════════════════════════════════════════

impl GlobalDispatch<ZwlrScreencopyManagerV1, ()> for State {
    fn bind(
        _state: &mut State,
        _handle: &DisplayHandle,
        _client: &Client,
        resource: New<ZwlrScreencopyManagerV1>,
        _global_data: &(),
        data_init: &mut DataInit<'_, State>,
    ) {
        data_init.init(resource, ());
    }
}

impl Dispatch<ZwlrScreencopyManagerV1, ()> for State {
    fn request(
        state: &mut State,
        _client: &Client,
        _resource: &ZwlrScreencopyManagerV1,
        request: zwlr_screencopy_manager_v1::Request,
        _data: &(),
        _dhandle: &DisplayHandle,
        data_init: &mut DataInit<'_, State>,
    ) {
        match request {
            zwlr_screencopy_manager_v1::Request::CaptureOutput {
                frame,
                overlay_cursor: _,
                output: _,
            } => {
                // Whole-output capture. HART-comp has exactly ONE output (the winit
                // window); we ignore the `output` arg (a single-output compositor) and
                // capture the full current size.
                let size = comp_core::output_physical_size(state);
                let region = Rectangle::from_size((size.w, size.h).into());
                init_frame(state, frame, region, data_init);
            }
            zwlr_screencopy_manager_v1::Request::CaptureOutputRegion {
                frame,
                overlay_cursor: _,
                output: _,
                x,
                y,
                width,
                height,
            } => {
                // Region capture: clamp the requested rect to the output bounds so a
                // client can never read outside the framebuffer (the ExportMem contract
                // rejects an out-of-bounds region — we clamp rather than fail so a
                // slightly-oversized region still yields a sane capture).
                let out = comp_core::output_physical_size(state);
                let region = comp_core::clamp_region(x, y, width, height, out.w, out.h);
                init_frame(state, frame, region, data_init);
            }
            zwlr_screencopy_manager_v1::Request::Destroy => {}
            _ => {}
        }
    }
}

/// Create the frame object + tell the client what buffer to allocate (the `buffer`
/// event = format/size/stride, then v3 `buffer_done`). Xrgb8888, 4 bytes/px, stride =
/// width*4. The frame's user-data carries the region so `copy` knows what to read.
fn init_frame(
    _state: &mut State,
    frame: New<ZwlrScreencopyFrameV1>,
    region: Rectangle<i32, BufferCoord>,
    data_init: &mut DataInit<'_, State>,
) {
    let data = ScreencopyFrameData {
        region,
        used: AtomicBool::new(false),
    };
    let frame = data_init.init(frame, data);
    let w = region.size.w as u32;
    let h = region.size.h as u32;
    let stride = w * 4; // Xrgb8888 = 4 bytes per pixel.
    // `buffer` advertises the shm format + dimensions the client must allocate.
    frame.buffer(wl_shm::Format::Xrgb8888, w, h, stride);
    // v3: `buffer_done` says "no more buffer/linux_dmabuf events; pick one + copy".
    if frame.version() >= 3 {
        frame.buffer_done();
    }
}

// ════════════════════════════════════════════════════════════════════════════
// The frame object — `copy` / `copy_with_damage` enqueue the read-back; the render
// loop fills it. `destroy` is the destructor.
// ════════════════════════════════════════════════════════════════════════════

impl Dispatch<ZwlrScreencopyFrameV1, ScreencopyFrameData> for State {
    fn request(
        state: &mut State,
        _client: &Client,
        resource: &ZwlrScreencopyFrameV1,
        request: zwlr_screencopy_frame_v1::Request,
        data: &ScreencopyFrameData,
        _dhandle: &DisplayHandle,
        _data_init: &mut DataInit<'_, State>,
    ) {
        match request {
            zwlr_screencopy_frame_v1::Request::Copy { buffer } => {
                queue_copy(state, resource, data, buffer, false);
            }
            zwlr_screencopy_frame_v1::Request::CopyWithDamage { buffer } => {
                queue_copy(state, resource, data, buffer, true);
            }
            zwlr_screencopy_frame_v1::Request::Destroy => {}
            _ => {}
        }
    }
}

/// Validate the client buffer + enqueue the read-back (or `failed()` immediately on a
/// bad buffer / re-use / killswitch). The actual pixel copy happens on the next paint
/// (`service_pending_screencopy`) — this only checks + queues.
fn queue_copy(
    state: &mut State,
    frame: &ZwlrScreencopyFrameV1,
    data: &ScreencopyFrameData,
    buffer: WlBuffer,
    with_damage: bool,
) {
    // ── Kill-switch: the human cut `screen`. Refuse EVERY capture while blocked. ──
    if state.capture_blocked {
        info!("screencopy: capture blocked by the screen kill-switch — failing the frame");
        frame.failed();
        return;
    }

    // A frame object may be copied exactly once (protocol `already_used`).
    if data.used.swap(true, Ordering::SeqCst) {
        frame.post_error(
            zwlr_screencopy_frame_v1::Error::AlreadyUsed,
            "screencopy frame already used",
        );
        return;
    }

    // The destination MUST be an shm buffer of the advertised size/format. We read its
    // shm metadata; a non-shm (e.g. dmabuf) buffer or a size mismatch → `failed()`
    // (we advertised an shm `buffer` event, so a well-behaved client always sends shm).
    let expected_w = data.region.size.w;
    let expected_h = data.region.size.h;
    let ok = with_buffer_contents_mut(&buffer, |_ptr, _len, bd: BufferData| {
        let fmt_ok = matches!(
            bd.format,
            wl_shm::Format::Xrgb8888 | wl_shm::Format::Argb8888
        );
        fmt_ok && bd.width == expected_w && bd.height == expected_h
    })
    .unwrap_or_else(|err| {
        debug!(?err, "screencopy: with_buffer_contents_mut could not read the client shm buffer");
        false
    });

    if !ok {
        warn!(
            expected_w,
            expected_h, "screencopy: client buffer is not a matching shm buffer — failing"
        );
        frame.failed();
        return;
    }

    state.pending_screencopy.push(PendingScreencopy {
        frame: frame.clone(),
        buffer,
        region: data.region,
        with_damage,
    });
}

// ════════════════════════════════════════════════════════════════════════════
// The render-loop hook — drain queued frames against the JUST-PAINTED framebuffer.
// Called from winit.rs step (b) AFTER `frame.finish()` (so the GL commands are
// flushed) but while the `renderer` + `framebuffer` are still in scope.
// ════════════════════════════════════════════════════════════════════════════

/// Service every queued screencopy frame: read back the framebuffer region into the
/// client's shm buffer, then send `flags` + `ready` (or `failed`). Drains the queue
/// (every frame is one-shot). `output_transform` is the output's render transform
/// (Flipped180 on winit) so the captured pixels match what the user sees upright.
///
/// The read-back uses `ExportMem::copy_framebuffer` (a glReadPixels under the hood on
/// the Gles path) → `map_texture` (the CPU-side bytes) → memcpy into the shm map. The
/// captured frame is EXACTLY the displayed frame (cursor + effects + killswitch
/// surface all painted into `framebuffer` already), which is the whole point of
/// capturing HART-comp's own output rather than the host re-composite.
pub fn service_pending_screencopy(
    state: &mut State,
    renderer: &mut GlesRenderer,
    framebuffer: &GlesTarget<'_>,
    output_size: Size<i32, Physical>,
    output_transform: Transform,
) {
    if state.pending_screencopy.is_empty() {
        return;
    }
    // Drain — each frame is one-shot (copy'd once).
    let pending = std::mem::take(&mut state.pending_screencopy);
    for p in pending {
        match fill_one(renderer, framebuffer, &p, output_size, output_transform) {
            Ok(()) => {}
            Err(e) => {
                warn!(error = %e, "screencopy: read-back failed — failing the frame");
                p.frame.failed();
            }
        }
    }
}

/// Read back ONE frame's region + copy it into the client buffer + signal ready.
/// Separated so the `?` early-returns map to a single `failed()` at the call site.
fn fill_one(
    renderer: &mut GlesRenderer,
    framebuffer: &GlesTarget<'_>,
    p: &PendingScreencopy,
    output_size: Size<i32, Physical>,
    output_transform: Transform,
) -> Result<(), String> {
    // The framebuffer is stored in the output's RENDER transform (Flipped180 on
    // winit). `copy_framebuffer` reads the RAW framebuffer, so to hand the client an
    // upright image we map the logical capture region through the transform to the
    // physical framebuffer rectangle. Flipped180 is a Y-axis flip (x preserved): the
    // mapped rect for a full-output capture is the same rect; for a sub-region only the
    // y origin moves (`area.h - y - height`). `Transform::transform_rect_in` does exactly
    // this.
    let fb_region = comp_core::transform_region(p.region, output_size, output_transform);

    // Read back the framebuffer pixels (Xrgb8888) for the region.
    let mapping = renderer
        .copy_framebuffer(framebuffer, fb_region, CAPTURE_FOURCC)
        .map_err(|e| format!("copy_framebuffer: {e:?}"))?;
    let pixels: &[u8] = renderer
        .map_texture(&mapping)
        .map_err(|e| format!("map_texture: {e:?}"))?;

    let src_w = p.region.size.w as usize;
    let src_h = p.region.size.h as usize;
    let src_stride = src_w * 4;
    if pixels.len() < src_stride * src_h {
        return Err(format!(
            "read-back too small: {} < {}",
            pixels.len(),
            src_stride * src_h
        ));
    }

    // Copy into the client's shm buffer row-by-row (honour the client's stride; it may
    // differ from ours if the client over-allocated). If the output transform
    // y-inverts relative to the client's expectation we flip rows so the PNG is
    // upright — but we already mapped the region through the transform above and report
    // no y_invert flag, so a straight row copy is correct here.
    let copied = with_buffer_contents_mut(&p.buffer, |ptr, len, bd: BufferData| {
        let dst_stride = bd.stride as usize;
        let dst_off = bd.offset as usize;
        let rows = src_h.min(bd.height as usize);
        let row_bytes = src_stride.min(dst_stride);
        // Map the shm-format byte order: our read-back is Fourcc::Xrgb8888 (little-
        // endian BGRX in memory, matching wl_shm Xrgb8888), so a direct row copy lands
        // the right bytes for an Xrgb/Argb client buffer.
        // The ONLY unsafe in this crate (see Cargo.toml [lints.rust]): Smithay hands
        // the shm mapping as a raw `*mut u8` + `len`, with no safe write helper for the
        // wlr-screencopy copy at this pinned rev. We build a checked `&mut [u8]` over the
        // mapping ONCE and write rows through safe slicing thereafter.
        // SAFETY: `with_buffer_contents_mut`'s contract guarantees `ptr` is a valid,
        // uniquely-borrowed, writable mapping of exactly `len` bytes for the duration of
        // this closure (it holds the pool lock). `u8` has no alignment/init requirements.
        // No other reference to this mapping exists while the closure runs.
        #[allow(unsafe_code)]
        let dst: &mut [u8] = unsafe { std::slice::from_raw_parts_mut(ptr, len) };
        for row in 0..rows {
            let s = row * src_stride;
            let d = dst_off + row * dst_stride;
            if d + row_bytes > len || s + row_bytes > pixels.len() {
                break;
            }
            dst[d..d + row_bytes].copy_from_slice(&pixels[s..s + row_bytes]);
        }
        rows
    })
    .map_err(|e| format!("with_buffer_contents_mut: {e:?}"))?;

    if copied == 0 {
        return Err("copied 0 rows".into());
    }

    // Tell the client the result is upright (no y-invert; we already corrected the
    // transform), then signal completion with a presentation timestamp.
    p.frame.flags(zwlr_screencopy_frame_v1::Flags::empty());
    if p.with_damage && p.frame.version() >= 2 {
        // We always have full damage on the single output.
        p.frame.damage(
            0,
            0,
            p.region.size.w as u32,
            p.region.size.h as u32,
        );
    }
    let (sec, nsec) = comp_core::now_secs_nsecs();
    let tv_sec_hi = (sec >> 32) as u32;
    let tv_sec_lo = (sec & 0xFFFF_FFFF) as u32;
    p.frame.ready(tv_sec_hi, tv_sec_lo, nsec);
    Ok(())
}

// The PURE region/time helpers — `clamp_region`, `transform_region`, `now_secs_nsecs` —
// live in comp_core.rs under the shared `any(winit, smithay)` cfg (this file is
// `#![cfg(feature = "winit")]`, so a `cargo test --features smithay` build — what
// hart-comp.nix's doCheck runs — would never compile them or their tests here). The
// handlers above CALL them via `comp_core::` (one source of truth, no parallel path);
// their unit floor rides comp_core.rs's #[cfg(test)] block, so the smithay doCheck
// exercises it.

// A tiny re-export so winit.rs can check shm-format support symmetrically if needed.
#[allow(unused)]
pub(crate) fn shm_supported(format: wl_shm::Format) -> bool {
    shm_format_to_fourcc(format).is_some()
}

// ════════════════════════════════════════════════════════════════════════════
// Capture-FORMAT invariant floor (M6 screencopy). The PURE region/time math floor
// (clamp_region / transform_region / now_secs_nsecs) moved WITH those helpers into
// comp_core.rs, so the smithay-feature `doCheck` exercises it (screencopy.rs is
// `#![cfg(feature = "winit")]` and would NOT compile under `--features smithay`).
// What stays here are the format invariants that touch THIS file's own items
// (`CAPTURE_FOURCC`, `shm_supported`) — computable in isolation with NO live renderer /
// GlesRenderer / wl_buffer. The killswitch gate + the shm-buffer validation in
// `queue_copy` are exercised live via the M6 grim-capture harness (they need a real
// `State` + client buffer). Compiled only under `--features winit`.
// ════════════════════════════════════════════════════════════════════════════
#[cfg(test)]
mod tests {
    use super::*;

    // ── format invariants ──

    #[test]
    fn capture_fourcc_is_the_mandatory_opaque_format() {
        assert_eq!(CAPTURE_FOURCC, Fourcc::Xrgb8888, "we advertise the opaque Xrgb floor");
    }

    #[test]
    fn shm_supported_accepts_the_wlr_capture_formats() {
        // grim/wf-recorder always allocate Xrgb8888 or Argb8888 — both must map to a
        // Fourcc (the read-back copies straight into either).
        assert!(shm_supported(wl_shm::Format::Xrgb8888));
        assert!(shm_supported(wl_shm::Format::Argb8888));
    }
}
