//! The A2UI home payload the SHELL actually produces, frozen for the native decoder.
//!
//! GENERATED, not hand-written. `tests/unit/test_native_wire_contract.py` runs the real
//! `liquid_ui_service._sanitize_home_payload` on a realistic LLM-authored home and asserts
//! this string still matches it byte for byte, so a change to the wire shape fails there
//! with the regeneration command rather than silently leaving the decoder tested against a
//! payload no producer sends any more. That is not hypothetical: the decoder once read
//! four keys (`hero.title`, `hero.copy`, `row.label`, `card.subtitle`) that NO producer has
//! ever emitted, and every unit test passed because each side built its own fixtures.
//!
//! A `.rs` file rather than the `.json` it obviously is, for one build reason: the crane
//! source filter keeps `Cargo.toml`/`Cargo.lock` and `*.rs` ONLY (hart-comp.nix says so at
//! its `compCleanSrc`), so a `.json` beside the crate would be filtered out of the build
//! sandbox and `include_str!` would fail in CI while passing locally.
//!
//! Two literals, not one, because a contract pinned on a single payload proves the
//! decoder against a single shape. The default carries an Aura mood (accent pinned teal,
//! the quad driving only the ambient field); the second carries a CLASSIC mood (the
//! accent set from the lead hue) and photos that name two of the bundled SVGs by their
//! real served paths. Each is regenerated by the same Python test from its own SAMPLE.

/// The verbatim output of the home-compose sanitizer. Test-only.
#[cfg(test)]
pub const HOME_COMPOSE_SANITIZED: &str = r##"{
  "hero": {
    "agents": 3,
    "amount": 1284,
    "amount_unit": "Spark",
    "eyebrow": "Earned on the hive",
    "local": true,
    "payout_pending": true,
    "primary": {
      "action": "resume",
      "label": "Resume",
      "target": "recipes"
    },
    "secondary": {
      "action": "ask",
      "label": "Ask anything"
    },
    "tasks": 7
  },
  "mood": "aurora",
  "palette": {
    "accent": "#00E6C3",
    "ambient_1": "#B182FF",
    "ambient_2": "#00DDF9",
    "ambient_3": "#FB66B6",
    "ambient_4": "#FFB330",
    "background": "#04050B",
    "secondary": "#00DDF9"
  },
  "rows": [
    {
      "accent": "teal",
      "cards": [
        {
          "action": "resume",
          "icon": "code",
          "meta": "3 files changed",
          "progress": 0.62,
          "target": "recipes",
          "title": "Refactor the parser",
          "topic": "Refactor the parser"
        },
        {
          "action": "open",
          "image_url": "https://example.invalid/a.jpg",
          "live": "RUNNING",
          "meta": "12 sources",
          "title": "Morning briefing",
          "topic": "Morning briefing"
        }
      ],
      "see_all": "recipes",
      "title": "Continue"
    },
    {
      "accent": "magenta",
      "cards": [
        {
          "action": "open",
          "badge": "NEW",
          "icon": "explore",
          "meta": "412 tasks",
          "title": "Scout",
          "topic": "Scout"
        },
        {
          "action": "open",
          "image": "/shell/static/app_art/a.svg",
          "meta": "388 tasks",
          "title": "Archivist",
          "topic": "Archivist"
        }
      ],
      "ranked": true,
      "see_all": "agents_browse",
      "title": "Top agents"
    }
  ]
}"##;

/// The sanitizer's output for a CLASSIC mood (`sunset`) with bundled-SVG photos. Test-only.
#[cfg(test)]
pub const HOME_COMPOSE_SANITIZED_CLASSIC_MOOD: &str = r##"{
  "hero": {
    "agents": 1,
    "amount": 96,
    "amount_unit": "Spark",
    "eyebrow": "Earned on the hive",
    "local": true,
    "payout_pending": true,
    "primary": {
      "action": "resume",
      "label": "Resume",
      "target": "recipes"
    },
    "secondary": {
      "action": "ask",
      "label": "Ask anything"
    },
    "tasks": 2
  },
  "mood": "sunset",
  "palette": {
    "accent": "#FF8A4C",
    "ambient_1": "#FF8A4C",
    "ambient_2": "#FF2E9A",
    "background": "#16090F",
    "secondary": "#FF2E9A"
  },
  "rows": [
    {
      "accent": "amber",
      "cards": [
        {
          "action": "open",
          "image": "/shell/static/app_art/apps/com.brave.Browser.svg",
          "meta": "Browser",
          "title": "Brave",
          "topic": "Brave"
        },
        {
          "action": "open",
          "image": "/shell/static/app_art/app-files.svg",
          "meta": "Everything you own",
          "title": "Files",
          "topic": "Files"
        }
      ],
      "see_all": "app_store",
      "title": "Apps"
    }
  ]
}"##;

/// The verbatim output of the BAR-content producer, `compose_shell_chrome`: the
/// `shell.chrome` half of the same contract (IPC_PROTOCOL.md 4.13), pinned by the same
/// Python test for the same reason. The bars' decoder must be tested against what the
/// shell SENDS, and the shell's tray glyphs, agent chips and clock text are exactly the
/// kind of thing a hand-written fixture gets plausibly wrong. Test-only.
#[cfg(test)]
pub const SHELL_CHROME_COMPOSED: &str = r##"{
  "agents": [
    "Scout",
    "summarise_inbox_",
    "Archivist",
    "Cartographer"
  ],
  "clock": {
    "date": "Wednesday, September 23",
    "time": "02:05 PM"
  },
  "menu": {
    "items": [
      {
        "icon": "open_in_new",
        "label": "Open"
      },
      {
        "sep": true
      },
      {
        "danger": true,
        "label": "Delete"
      },
      {
        "disabled": true,
        "label": "Rename"
      }
    ],
    "x": 412,
    "y": 300
  },
  "notifications": {
    "unread": 2
  },
  "start": {
    "open": false
  },
  "tasks": [
    {
      "active": true,
      "icon": "folder",
      "id": "files",
      "title": "Files"
    },
    {
      "active": false,
      "icon": "terminal",
      "id": "terminal",
      "title": "Terminal"
    },
    {
      "active": false,
      "id": "web#2",
      "title": "Hevolve bdocs/b"
    }
  ],
  "toast": {
    "message": "Not available",
    "severity": "warning",
    "title": "Bluetooth"
  },
  "tray": {
    "battery": "battery_4_bar",
    "battery_pct": "64%",
    "bluetooth": "bluetooth_connected",
    "live": true,
    "volume": "volume_down",
    "wifi": "network_wifi_3_bar"
  }
}"##;
