//! The A2UI home payload the SHELL actually produces, frozen for the native decoder.
//!
//! GENERATED, not hand-written. `tests/unit/test_native_wire_contract.py` runs the real
//! `liquid_ui_service._sanitize_home_payload` on a realistic LLM-authored home and asserts
//! this string still matches it byte for byte, so a change to the wire shape fails there
//! with the regeneration command rather than silently leaving the decoder tested against a
//! payload no producer sends any more. That is not hypothetical: the decoder once read
//! four keys (`hero.title`, `hero.copy`, `row.label`, `card.subtitle`) that NO producer has
//! ever emitted, and every unit test passed because each side built its own fixtures.
//!
//! A `.rs` file rather than the `.json` it obviously is, for one build reason: the crane
//! source filter keeps `Cargo.toml`/`Cargo.lock` and `*.rs` ONLY (hart-comp.nix says so at
//! its `compCleanSrc`), so a `.json` beside the crate would be filtered out of the build
//! sandbox and `include_str!` would fail in CI while passing locally.
//!
//! Two literals, not one, because a contract pinned on a single payload proves the
//! decoder against a single shape. The default carries an Aura mood (accent pinned teal,
//! the quad driving only the ambient field); the second carries a CLASSIC mood (the
//! accent set from the lead hue) and photos that name two of the bundled SVGs by their
//! real served paths. Each is regenerated by the same Python test from its own SAMPLE.

/// The verbatim output of the home-compose sanitizer. Test-only.
#[cfg(test)]
pub const HOME_COMPOSE_SANITIZED: &str = r##"{
  "hero": {
    "agents": 3,
    "amount": 1284,
    "amount_unit": "Spark",
    "eyebrow": "Earned on the hive",
    "local": true,
    "payout_pending": true,
    "primary": {
      "action": "resume",
      "label": "Resume",
      "target": "recipes"
    },
    "secondary": {
      "action": "ask",
      "label": "Ask anything"
    },
    "tasks": 7
  },
  "mood": "aurora",
  "palette": {
    "accent": "#00E6C3",
    "ambient_1": "#B182FF",
    "ambient_2": "#00DDF9",
    "ambient_3": "#FB66B6",
    "ambient_4": "#FFB330",
    "background": "#04050B",
    "secondary": "#00DDF9"
  },
  "rows": [
    {
      "accent": "teal",
      "cards": [
        {
          "action": "resume",
          "icon": "code",
          "meta": "3 files changed",
          "progress": 0.62,
          "target": "recipes",
          "title": "Refactor the parser",
          "topic": "Refactor the parser"
        },
        {
          "action": "open",
          "image_url": "https://example.invalid/a.jpg",
          "live": "RUNNING",
          "meta": "12 sources",
          "title": "Morning briefing",
          "topic": "Morning briefing"
        }
      ],
      "see_all": "recipes",
      "title": "Continue"
    },
    {
      "accent": "magenta",
      "cards": [
        {
          "action": "open",
          "badge": "NEW",
          "icon": "explore",
          "meta": "412 tasks",
          "title": "Scout",
          "topic": "Scout"
        },
        {
          "action": "open",
          "image": "/shell/static/app_art/a.svg",
          "meta": "388 tasks",
          "title": "Archivist",
          "topic": "Archivist"
        }
      ],
      "ranked": true,
      "see_all": "agents_browse",
      "title": "Top agents"
    }
  ]
}"##;

/// The sanitizer's output for a CLASSIC mood (`sunset`) with bundled-SVG photos. Test-only.
#[cfg(test)]
pub const HOME_COMPOSE_SANITIZED_CLASSIC_MOOD: &str = r##"{
  "hero": {
    "agents": 1,
    "amount": 96,
    "amount_unit": "Spark",
    "eyebrow": "Earned on the hive",
    "local": true,
    "payout_pending": true,
    "primary": {
      "action": "resume",
      "label": "Resume",
      "target": "recipes"
    },
    "secondary": {
      "action": "ask",
      "label": "Ask anything"
    },
    "tasks": 2
  },
  "mood": "sunset",
  "palette": {
    "accent": "#FF8A4C",
    "ambient_1": "#FF8A4C",
    "ambient_2": "#FF2E9A",
    "background": "#16090F",
    "secondary": "#FF2E9A"
  },
  "rows": [
    {
      "accent": "amber",
      "cards": [
        {
          "action": "open",
          "image": "/shell/static/app_art/apps/com.brave.Browser.svg",
          "meta": "Browser",
          "title": "Brave",
          "topic": "Brave"
        },
        {
          "action": "open",
          "image": "/shell/static/app_art/app-files.svg",
          "meta": "Everything you own",
          "title": "Files",
          "topic": "Files"
        }
      ],
      "see_all": "app_store",
      "title": "Apps"
    }
  ]
}"##;

/// The verbatim output of the BAR-content producer, `compose_shell_chrome`: the
/// `shell.chrome` half of the same contract (IPC_PROTOCOL.md 4.13), pinned by the same
/// Python test for the same reason. The bars' decoder must be tested against what the
/// shell SENDS, and the shell's tray glyphs, agent chips and clock text are exactly the
/// kind of thing a hand-written fixture gets plausibly wrong. Test-only.
#[cfg(test)]
pub const SHELL_CHROME_COMPOSED: &str = r##"{
  "agents": [
    "Scout",
    "summarise_inbox_",
    "Archivist",
    "Cartographer"
  ],
  "clock": {
    "date": "Wednesday, September 23",
    "time": "02:05 PM"
  },
  "menu": {
    "items": [
      {
        "icon": "open_in_new",
        "label": "Open"
      },
      {
        "sep": true
      },
      {
        "danger": true,
        "label": "Delete"
      },
      {
        "disabled": true,
        "label": "Rename"
      }
    ],
    "x": 412,
    "y": 300
  },
  "notifications": {
    "unread": 2
  },
  "start": {
    "open": false
  },
  "tasks": [
    {
      "active": true,
      "icon": "folder",
      "id": "files",
      "title": "Files"
    },
    {
      "active": false,
      "icon": "terminal",
      "id": "terminal",
      "title": "Terminal"
    },
    {
      "active": false,
      "id": "web#2",
      "title": "Hevolve bdocs/b"
    }
  ],
  "toast": {
    "message": "Not available",
    "severity": "warning",
    "title": "Bluetooth"
  },
  "tray": {
    "battery": "battery_4_bar",
    "battery_pct": "64%",
    "bluetooth": "bluetooth_connected",
    "live": true,
    "volume": "volume_down",
    "wifi": "network_wifi_3_bar"
  }
}"##;

/// Every bundled card SVG (`integrations/agent_engine/static/app_art/**/*.svg`), by its
/// path relative to `app_art`, verbatim. Pinned by the same Python test so the native
/// rasteriser is proven against the files the shell actually serves, and a new or
/// edited asset that the compositor cannot decode fails in CI rather than on a card.
/// The crane source filter is why these live in a `.rs` (see the module header).
/// Test-only.
#[cfg(test)]
pub const BUNDLED_CARD_ART: &[(&str, &str)] = &[
    ("agent-auto-research.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Auto Research'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#29C5FF' stop-opacity='.55'/><stop offset='52%' stop-color='#3B82F6' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#29C5FF' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#29C5FF' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><g fill='none' stroke='#EAF6FF' stroke-opacity='.85' stroke-width='9' stroke-linecap='round'><circle cx='228' cy='140' r='40'/><line x1='258' y1='170' x2='294' y2='206'/></g><g fill='#EAF6FF' fill-opacity='.7'><circle cx='208' cy='94' r='6'/><circle cx='300' cy='116' r='5'/><circle cx='196' cy='192' r='5'/></g><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("agent-english-learning.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='English Learning'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#FFC83D' stop-opacity='.55'/><stop offset='52%' stop-color='#FF2E9A' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#FFC83D' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#FFC83D' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><g fill='none' stroke='#EAF6FF' stroke-opacity='.85' stroke-width='8' stroke-linejoin='round'><path d='M240 110 Q206 96 176 104 V196 Q206 188 240 200 Z'/><path d='M240 110 Q274 96 304 104 V196 Q274 188 240 200 Z'/></g><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("agent-speech-therapy.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Speech Therapy'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#FF2E9A' stop-opacity='.55'/><stop offset='52%' stop-color='#9B5CFF' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#FF2E9A' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#FF2E9A' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><g stroke='#EAF6FF' stroke-opacity='.85' stroke-width='10' stroke-linecap='round'><line x1='180' y1='138' x2='180' y2='162'/><line x1='206' y1='116' x2='206' y2='184'/><line x1='232' y1='94' x2='232' y2='206'/><line x1='258' y1='110' x2='258' y2='190'/><line x1='284' y1='128' x2='284' y2='172'/><line x1='308' y1='120' x2='308' y2='180'/></g><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("agent-spoken-english.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Spoken English'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#00E6C3' stop-opacity='.55'/><stop offset='52%' stop-color='#29C5FF' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#00E6C3' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#00E6C3' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><circle cx='206' cy='150' r='20' fill='#EAF6FF' fill-opacity='.85'/><g fill='none' stroke='#EAF6FF' stroke-opacity='.8' stroke-width='8' stroke-linecap='round'><path d='M250 120 Q274 150 250 180'/><path d='M280 102 Q316 150 280 198'/></g><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("agent-trading.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Trading'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#34C759' stop-opacity='.55'/><stop offset='52%' stop-color='#00E6C3' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#34C759' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#34C759' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><g stroke='#EAF6FF' stroke-opacity='.8' stroke-width='4'><line x1='196' y1='96' x2='196' y2='210'/><line x1='228' y1='110' x2='228' y2='200'/><line x1='260' y1='84' x2='260' y2='196'/><line x1='292' y1='120' x2='292' y2='214'/></g><g fill='#EAF6FF' fill-opacity='.85'><rect x='186' y='120' width='20' height='56' rx='3'/><rect x='218' y='132' width='20' height='44' rx='3'/><rect x='250' y='104' width='20' height='64' rx='3'/><rect x='282' y='150' width='20' height='40' rx='3'/></g><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("agent-tutor.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Tutor'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#9B5CFF' stop-opacity='.55'/><stop offset='52%' stop-color='#3B82F6' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#9B5CFF' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#9B5CFF' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><polygon points='240,104 312,140 240,176 168,140' fill='#EAF6FF' fill-opacity='.85'/><g fill='none' stroke='#EAF6FF' stroke-opacity='.85' stroke-width='8' stroke-linecap='round'><path d='M196 154 V190 Q240 214 284 190 V154'/><line x1='312' y1='140' x2='312' y2='184'/></g><circle cx='312' cy='190' r='6' fill='#EAF6FF'/><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("app-files.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Files'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#29C5FF' stop-opacity='.55'/><stop offset='52%' stop-color='#3B82F6' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#29C5FF' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#29C5FF' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><path d='M176 122 H216 L230 138 H306 V202 H176 Z' fill='#EAF6FF' fill-opacity='.85'/><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("app-hart-setup.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Light your HART'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#00E6C3' stop-opacity='.55'/><stop offset='52%' stop-color='#9B5CFF' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#00E6C3' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#00E6C3' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><path d='M240 202 C200 170 180 152 180 126 C180 108 196 96 214 96 C227 96 236 105 240 113 C244 105 253 96 266 96 C284 96 300 108 300 126 C300 152 280 170 240 202 Z' fill='#EAF6FF' fill-opacity='.9'/><g stroke='#EAF6FF' stroke-opacity='.55' stroke-width='6' stroke-linecap='round'><line x1='150' y1='150' x2='170' y2='150'/><line x1='310' y1='150' x2='330' y2='150'/><line x1='240' y1='68' x2='240' y2='86'/></g><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("app-security.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Security'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#34C759' stop-opacity='.55'/><stop offset='52%' stop-color='#00E6C3' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#34C759' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#34C759' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><path d='M240 100 L296 122 V160 Q296 196 240 212 Q184 196 184 160 V122 Z' fill='#EAF6FF' fill-opacity='.18' stroke='#EAF6FF' stroke-opacity='.85' stroke-width='8' stroke-linejoin='round'/><polyline points='216,154 234,172 268,132' fill='none' stroke='#EAF6FF' stroke-opacity='.9' stroke-width='9' stroke-linecap='round' stroke-linejoin='round'/><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("app-store.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='App Store'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#FFC83D' stop-opacity='.55'/><stop offset='52%' stop-color='#FF2E9A' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#FFC83D' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#FFC83D' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><path d='M180 120 H300 L314 150 H166 Z' fill='#EAF6FF' fill-opacity='.85'/><rect x='178' y='150' width='124' height='66' rx='4' fill='none' stroke='#EAF6FF' stroke-opacity='.85' stroke-width='8'/><rect x='222' y='176' width='36' height='40' rx='3' fill='#EAF6FF' fill-opacity='.85'/><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("app-terminal.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Terminal'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#34C759' stop-opacity='.55'/><stop offset='52%' stop-color='#00E6C3' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#34C759' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#34C759' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><g fill='none' stroke='#EAF6FF' stroke-opacity='.85' stroke-width='10' stroke-linecap='round' stroke-linejoin='round'><polyline points='186,116 224,150 186,184'/><line x1='238' y1='192' x2='302' y2='192'/></g><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("app-weather.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300' width='480' height='300' preserveAspectRatio='xMidYMid slice' role='img' aria-label='Weather'><defs><radialGradient id='b' cx='38%' cy='32%' r='82%'><stop offset='0' stop-color='#29C5FF' stop-opacity='.55'/><stop offset='52%' stop-color='#3B82F6' stop-opacity='.20'/><stop offset='100%' stop-color='#06070D' stop-opacity='0'/></radialGradient><linearGradient id='s' x1='0' y1='0' x2='0' y2='1'><stop offset='.44' stop-color='#04050B' stop-opacity='0'/><stop offset='1' stop-color='#04050B' stop-opacity='.80'/></linearGradient></defs><rect width='480' height='300' fill='#070812'/><rect width='480' height='300' fill='url(#b)'/><g fill='none' stroke='#29C5FF' stroke-opacity='.13'><circle cx='240' cy='150' r='172'/><circle cx='240' cy='150' r='116'/></g><g fill='#29C5FF' fill-opacity='.45'><circle cx='240' cy='34' r='5'/><circle cx='356' cy='150' r='4'/><circle cx='150' cy='206' r='4'/><circle cx='330' cy='84' r='3'/></g><circle cx='288' cy='116' r='22' fill='#EAF6FF' fill-opacity='.85'/><path d='M196 198 Q174 198 174 176 Q174 158 196 156 Q200 130 228 130 Q254 130 260 156 Q286 156 286 178 Q286 198 264 198 Z' fill='#EAF6FF' fill-opacity='.85'/><rect width='480' height='300' fill='url(#s)'/></svg>"##),
    ("apps/com.brave.Browser.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Brave'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>B</text></svg>"##),
    ("apps/com.discordapp.Discord.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Discord'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#34C759'/><stop offset='1' stop-color='#00E6C3'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>D</text></svg>"##),
    ("apps/com.github.Anuken.Mindustry.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Mindustry'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF2E9A'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>M</text></svg>"##),
    ("apps/com.obsproject.Studio.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='OBS Studio'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#3B82F6'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>O</text></svg>"##),
    ("apps/com.play0ad.zeroad.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='0 A.D.'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FFC83D'/><stop offset='1' stop-color='#FF2E9A'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>0</text></svg>"##),
    ("apps/com.rustdesk.RustDesk.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='RustDesk'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF2E9A'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>R</text></svg>"##),
    ("apps/com.valvesoftware.Steam.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Steam'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#3B82F6'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>S</text></svg>"##),
    ("apps/com.visualstudio.code.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='VS Code'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#9B5CFF'/><stop offset='1' stop-color='#3B82F6'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>V</text></svg>"##),
    ("apps/dev.helix.Helix.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Helix'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>H</text></svg>"##),
    ("apps/io.bassi.Amberol.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Amberol'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#29C5FF'/><stop offset='1' stop-color='#3B82F6'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>A</text></svg>"##),
    ("apps/io.github.celluloid_player.Celluloid.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Celluloid'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FFC83D'/><stop offset='1' stop-color='#FF2E9A'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>C</text></svg>"##),
    ("apps/io.github.shiftey.Desktop.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='GitHub Desktop'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FFC83D'/><stop offset='1' stop-color='#FF2E9A'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>G</text></svg>"##),
    ("apps/md.obsidian.Obsidian.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Obsidian'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>O</text></svg>"##),
    ("apps/net.lutris.Lutris.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Lutris'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#00E6C3'/><stop offset='1' stop-color='#29C5FF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>L</text></svg>"##),
    ("apps/net.supertuxkart.SuperTuxKart.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='SuperTuxKart'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>S</text></svg>"##),
    ("apps/org.audacityteam.Audacity.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Audacity'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FFC83D'/><stop offset='1' stop-color='#FF2E9A'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>A</text></svg>"##),
    ("apps/org.blender.Blender.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Blender'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#34C759'/><stop offset='1' stop-color='#00E6C3'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>B</text></svg>"##),
    ("apps/org.chromium.Chromium.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Chromium'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#34C759'/><stop offset='1' stop-color='#00E6C3'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>C</text></svg>"##),
    ("apps/org.gimp.GIMP.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='GIMP'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#3B82F6'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>G</text></svg>"##),
    ("apps/org.gnome.Calculator.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Calculator'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#34C759'/><stop offset='1' stop-color='#00E6C3'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>C</text></svg>"##),
    ("apps/org.gnome.Console.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Console'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF2E9A'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>C</text></svg>"##),
    ("apps/org.gnome.DiskUtility.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Disks'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#00E6C3'/><stop offset='1' stop-color='#29C5FF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>D</text></svg>"##),
    ("apps/org.gnome.Epiphany.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='GNOME Web'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#29C5FF'/><stop offset='1' stop-color='#3B82F6'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>G</text></svg>"##),
    ("apps/org.gnome.Fractal.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Fractal'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>F</text></svg>"##),
    ("apps/org.gnome.Nautilus.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Files'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>F</text></svg>"##),
    ("apps/org.gnome.SystemMonitor.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='System Monitor'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>S</text></svg>"##),
    ("apps/org.gnome.TextEditor.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Text Editor'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#3B82F6'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>T</text></svg>"##),
    ("apps/org.inkscape.Inkscape.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Inkscape'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#29C5FF'/><stop offset='1' stop-color='#3B82F6'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>I</text></svg>"##),
    ("apps/org.kde.kdenlive.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Kdenlive'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#9B5CFF'/><stop offset='1' stop-color='#3B82F6'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>K</text></svg>"##),
    ("apps/org.kde.krita.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Krita'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FFC83D'/><stop offset='1' stop-color='#FF2E9A'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>K</text></svg>"##),
    ("apps/org.libreoffice.LibreOffice.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='LibreOffice'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#29C5FF'/><stop offset='1' stop-color='#3B82F6'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>L</text></svg>"##),
    ("apps/org.mozilla.Thunderbird.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Thunderbird'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>T</text></svg>"##),
    ("apps/org.mozilla.firefox.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Firefox'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>F</text></svg>"##),
    ("apps/org.pitivi.Pitivi.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Pitivi'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#3B82F6'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>P</text></svg>"##),
    ("apps/org.prismlauncher.PrismLauncher.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Prism Launcher'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#3B82F6'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>P</text></svg>"##),
    ("apps/org.signal.Signal.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Signal'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#29C5FF'/><stop offset='1' stop-color='#3B82F6'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>S</text></svg>"##),
    ("apps/org.telegram.desktop.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Telegram'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FF7043'/><stop offset='1' stop-color='#FFC83D'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>T</text></svg>"##),
    ("apps/org.videolan.VLC.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='VLC'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#FFC83D'/><stop offset='1' stop-color='#FF2E9A'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>V</text></svg>"##),
    ("apps/rest.insomnia.Insomnia.svg", r##"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96' width='96' height='96' role='img' aria-label='Insomnia'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='#3B82F6'/><stop offset='1' stop-color='#9B5CFF'/></linearGradient></defs><rect x='6' y='6' width='84' height='84' rx='22' fill='#0b0d16'/><rect x='6' y='6' width='84' height='84' rx='22' fill='url(#g)' fill-opacity='.92'/><text x='48' y='48' text-anchor='middle' dominant-baseline='central' font-family='Segoe UI, Roboto, Helvetica, Arial, sans-serif' font-size='46' font-weight='700' fill='#F5FAFF' fill-opacity='.96'>I</text></svg>"##),
];
