"""
Hardened JWT Manager — Two-Layer Authentication

Layer 1 (LOCAL): Node's own HS256 secret signs local JWTs.
    Works offline, survives kill switch, survives central outage.
Layer 2 (HIVE): HS256 + Ed25519 node_sig for cross-node identity.
    Certificate chain verified — killed by master key revocation.

The master key NEVER appears in JWT signing, token verification, or local auth.
The master key's SOLE purpose is the kill switch for the distributed intelligence.
"""

import json
import os
import time
import uuid
import logging
import hashlib
import hmac
from typing import Optional, Tuple
from functools import lru_cache

logger = logging.getLogger('hevolve_security')

try:
    import jwt as pyjwt
    HAS_JWT = True
except ImportError:
    HAS_JWT = False

import sys as _sys
# Desktop apps need long-lived sessions — users don't re-login daily.
# Cloud/server deploys should use short-lived tokens via env override.
_BUNDLED = getattr(_sys, 'frozen', False) or os.environ.get('NUNBA_BUNDLED')
ACCESS_TOKEN_EXPIRY = int(os.environ.get(
    'JWT_ACCESS_EXPIRY',
    30 * 86400 if _BUNDLED else 3600))   # 30 days bundled, 1 hour server
REFRESH_TOKEN_EXPIRY = int(os.environ.get(
    'JWT_REFRESH_EXPIRY',
    90 * 86400 if _BUNDLED else 86400 * 7))  # 90 days bundled, 7 days server
GRACE_PERIOD_EXPIRY = 86400 * 30    # 30 days - accept old tokens during migration


class TokenBlocklist:
    """In-memory token blocklist with optional Redis backend."""

    def __init__(self):
        self._memory_blocklist: set = set()
        self._redis = None
        self._init_redis()

    def _init_redis(self):
        try:
            import redis
            redis_url = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
            self._redis = redis.from_url(redis_url, decode_responses=True)
            self._redis.ping()
        except Exception:
            self._redis = None

    def add(self, jti: str, expires_in: int = ACCESS_TOKEN_EXPIRY):
        """Add a token JTI to the blocklist."""
        self._memory_blocklist.add(jti)
        if self._redis:
            try:
                self._redis.setex(f"jwt_blocklist:{jti}", expires_in, "1")
            except Exception:
                pass

    def is_blocked(self, jti: str) -> bool:
        """Check if a token JTI is blocked."""
        if jti in self._memory_blocklist:
            return True
        if self._redis:
            try:
                return self._redis.exists(f"jwt_blocklist:{jti}") > 0
            except Exception:
                pass
        return False


# Singleton blocklist
_blocklist = TokenBlocklist()


def _get_node_id() -> str:
    """Return the first 16 hex chars of this node's Ed25519 public key."""
    try:
        from security.node_integrity import get_public_key_hex
        return get_public_key_hex()[:16]
    except Exception:
        return 'unknown'


class JWTManager:
    """Secure JWT token management with two-layer auth.

    Layer 1 — LOCAL tokens:
        HS256 signed with per-node SOCIAL_SECRET_KEY.
        scope='local', iss='node:{node_id}'.
        Work offline. Survive kill switch.

    Layer 2 — HIVE tokens:
        HS256 + Ed25519 node_sig (in custom 'node_sig' claim).
        scope='hive', iss='hive:hevolve'.
        Verifiable by any node that knows the issuer's public key.
        Dies with certificate chain revocation (kill switch).
    """

    def __init__(self, secret_key: Optional[str] = None):
        self._secret_key = secret_key or self._load_secret_key()
        self._validate_secret_key()

    @staticmethod
    def _load_secret_key() -> str:
        key = os.environ.get('SOCIAL_SECRET_KEY', '')
        if not key:
            try:
                from security.secrets_manager import get_secret
                key = get_secret('SOCIAL_SECRET_KEY')
            except Exception:
                pass
        if not key:
            # Read from the persistent key file that auth.py creates.
            # This ensures JWTManager and legacy auth use the SAME key,
            # so tokens generated by either can be verified by either.
            for candidate in [
                os.path.join(os.environ.get('HEVOLVE_DB_PATH', ''), '..', '.social_secret_key'),
                os.path.join(os.path.expanduser('~'), 'Documents', 'Nunba', 'data', '.social_secret_key'),
                os.path.join('agent_data', '.social_secret_key'),
            ]:
                try:
                    candidate = os.path.normpath(candidate)
                    if os.path.exists(candidate):
                        with open(candidate, 'r') as f:
                            key = f.read().strip()
                        if len(key) >= 32:
                            break
                        key = ''
                except Exception:
                    continue
        return key

    def _validate_secret_key(self):
        """Reject weak/default secrets."""
        weak_defaults = [
            'hevolve-social-secret-change-in-production',
            'secret', 'changeme', 'password', '',
        ]
        if self._secret_key in weak_defaults:
            raise RuntimeError(
                "SOCIAL_SECRET_KEY is weak or default. "
                "Set a strong secret via environment variable."
            )
        if len(self._secret_key) < 32:
            logger.warning("SOCIAL_SECRET_KEY is shorter than 32 characters. Consider using a longer key.")

    def generate_access_token(self, user_id: str, username: str) -> str:
        """Generate a short-lived LOCAL access token (1 hour)."""
        return self._generate_token(
            user_id, username, 'access', ACCESS_TOKEN_EXPIRY, scope='local'
        )

    def generate_refresh_token(self, user_id: str, username: str) -> str:
        """Generate a LOCAL refresh token (7 days)."""
        return self._generate_token(
            user_id, username, 'refresh', REFRESH_TOKEN_EXPIRY, scope='local'
        )

    def generate_token_pair(self, user_id: str, username: str) -> dict:
        """Generate both access and refresh tokens (local scope)."""
        return {
            'access_token': self.generate_access_token(user_id, username),
            'refresh_token': self.generate_refresh_token(user_id, username),
            'token_type': 'bearer',
            'expires_in': ACCESS_TOKEN_EXPIRY,
            'scope': 'local',
        }

    def _generate_token(self, user_id: str, username: str,
                        token_type: str, expiry: int,
                        scope: str = 'local') -> str:
        if not HAS_JWT:
            return self._generate_hmac_token(user_id, username)

        node_id = _get_node_id()
        payload = {
            'user_id': user_id,
            'username': username,
            'jti': str(uuid.uuid4()),
            'iat': int(time.time()),
            'exp': int(time.time()) + expiry,
            'type': token_type,
            'scope': scope,
            'node_id': node_id,
            'iss': f'node:{node_id}' if scope == 'local' else 'hive:hevolve',
        }
        return pyjwt.encode(payload, self._secret_key, algorithm='HS256')

    def _generate_hmac_token(self, user_id: str, username: str) -> str:
        """Fallback token generation without PyJWT."""
        raw = f"{user_id}:{username}:{time.time()}:{uuid.uuid4()}"
        return hmac.new(
            self._secret_key.encode(), raw.encode(), hashlib.sha256
        ).hexdigest()

    def decode_token(self, token: str, expected_type: str = 'access') -> Optional[dict]:
        """Decode and validate a JWT token (any scope).

        Backward compatible: tokens without 'scope' are treated as local.
        Returns payload dict or None if invalid.
        """
        if not HAS_JWT:
            return None

        try:
            payload = pyjwt.decode(
                token, self._secret_key, algorithms=['HS256']
            )

            # Check token type
            token_type = payload.get('type', 'access')
            if token_type != expected_type:
                logger.warning(f"Token type mismatch: expected {expected_type}, got {token_type}")
                return None

            # Check blocklist
            jti = payload.get('jti')
            if jti and _blocklist.is_blocked(jti):
                logger.warning(f"Blocked token used: jti={jti}")
                return None

            return payload

        except pyjwt.ExpiredSignatureError:
            return None
        except pyjwt.InvalidTokenError as e:
            logger.warning(f"Invalid token: {e}")
            return None

    def revoke_token(self, token: str):
        """Revoke a token by adding its JTI to the blocklist."""
        if not HAS_JWT:
            return

        try:
            # Decode without verification to get JTI (token may already be expired)
            payload = pyjwt.decode(
                token, self._secret_key, algorithms=['HS256'],
                options={'verify_exp': False}
            )
            jti = payload.get('jti')
            if jti:
                exp = payload.get('exp', 0)
                ttl = max(exp - int(time.time()), ACCESS_TOKEN_EXPIRY)
                _blocklist.add(jti, ttl)
                logger.info(f"Token revoked: jti={jti}")
        except Exception:
            pass

    def refresh_access_token(self, refresh_token: str) -> Optional[dict]:
        """
        Use a refresh token to generate a new access token.
        Returns new token pair or None if refresh token is invalid.
        """
        payload = self.decode_token(refresh_token, expected_type='refresh')
        if not payload:
            return None

        # Revoke old refresh token (rotation)
        self.revoke_token(refresh_token)

        return self.generate_token_pair(
            payload['user_id'], payload['username']
        )

    # ── Layer 2: Hive tokens ────────────────────────────────────

    def generate_hive_token(self, user_id: str, username: str) -> str:
        """Generate a hive-scoped access token with Ed25519 node signature.

        The JWT is HS256-signed (readable by this node) AND carries a
        'node_sig' claim: the Ed25519 signature over the canonical payload
        (minus node_sig itself).  Any peer that knows our public key can
        verify the node_sig without needing our HS256 secret.
        """
        if not HAS_JWT:
            return self._generate_hmac_token(user_id, username)

        node_id = _get_node_id()
        payload = {
            'user_id': user_id,
            'username': username,
            'jti': str(uuid.uuid4()),
            'iat': int(time.time()),
            'exp': int(time.time()) + ACCESS_TOKEN_EXPIRY,
            'type': 'access',
            'scope': 'hive',
            'node_id': node_id,
            'iss': 'hive:hevolve',
        }

        # Sign the payload with this node's Ed25519 key
        try:
            from security.node_integrity import sign_json_payload
            payload['node_sig'] = sign_json_payload(payload)
        except Exception as e:
            logger.warning(f"Could not sign hive token with Ed25519: {e}")
            # Still produce a valid JWT, just without cross-node verifiability
            payload['node_sig'] = ''

        return pyjwt.encode(payload, self._secret_key, algorithm='HS256')

    def verify_hive_token(self, token: str,
                          issuer_public_key_hex: str) -> Optional[dict]:
        """Verify a hive-scoped token from another node.

        Two verification paths:
          1. If we share the HS256 secret (same node or shared secret):
             decode normally, then also verify node_sig.
          2. If we only have the issuer's Ed25519 public key:
             decode WITHOUT HS256 verification, then verify node_sig.

        Returns the payload dict on success, None on failure.
        """
        if not HAS_JWT:
            return None

        payload = None

        # Path 1: try HS256 decode (works if this is the issuing node)
        try:
            payload = pyjwt.decode(
                token, self._secret_key, algorithms=['HS256']
            )
        except (pyjwt.InvalidTokenError, pyjwt.ExpiredSignatureError):
            pass

        # Path 2: decode without HS256 verification (cross-node)
        if payload is None:
            try:
                payload = pyjwt.decode(
                    token, options={
                        'verify_signature': False,
                        'verify_exp': True,
                    }, algorithms=['HS256']
                )
            except (pyjwt.ExpiredSignatureError, pyjwt.InvalidTokenError):
                return None

        if not payload:
            return None

        # Must be a hive token
        if payload.get('scope') != 'hive':
            logger.warning("verify_hive_token called on non-hive token")
            return None

        # Check blocklist
        jti = payload.get('jti')
        if jti and _blocklist.is_blocked(jti):
            logger.warning(f"Blocked hive token used: jti={jti}")
            return None

        # Verify Ed25519 node_sig
        node_sig = payload.get('node_sig', '')
        if not node_sig:
            logger.warning("Hive token missing node_sig claim")
            return None

        try:
            from security.node_integrity import verify_json_signature
            # Strip node_sig from payload before verification — it was not
            # present when the signature was computed during generation.
            verify_payload = {k: v for k, v in payload.items()
                             if k != 'node_sig'}
            if not verify_json_signature(
                    issuer_public_key_hex, verify_payload, node_sig):
                logger.warning("Hive token node_sig verification failed")
                return None
        except Exception as e:
            logger.warning(f"Hive token Ed25519 verification error: {e}")
            return None

        return payload

    def decode_local_token(self, token: str,
                           expected_type: str = 'access') -> Optional[dict]:
        """Decode a local-scoped token. Backward compatible.

        Tokens without a 'scope' claim are treated as local (pre-upgrade tokens).
        Rejects hive-scoped tokens — use verify_hive_token() for those.
        """
        payload = self.decode_token(token, expected_type=expected_type)
        if payload is None:
            return None

        scope = payload.get('scope')
        if scope is not None and scope != 'local':
            logger.warning(
                f"decode_local_token rejected token with scope={scope}")
            return None

        return payload
