#!/bin/bash
# Canonical deepbox deploy — invoked by .github/workflows/deploy-hartos-deepbox.yml
# over SSH after the workflow's bootstrap has already: cd'd to the repo, reset
# to origin/main, and written oauth.env from the HARTOS_OAUTH_ENV secret.
#
# All configuration arrives as ENVIRONMENT VARIABLES (ssh-action `envs:` +
# step-level `env:` from repo secrets):
#   DEPLOY_LOGS_PATH DEPLOY_IMAGES_PATH DEPLOY_MASTER_KEY_PATH
#   DEPLOY_ADVERTISE_URL DEPLOY_AGENT_DATA_PATH LLM_GATEWAY_URL
#   GROQ_API_KEY LANGCHAIN_API_KEY ALLOWED_HOSTS CORS_ORIGINS HART_OTA_HOST
#   HEVOLVE_ENFORCEMENT_MODE HEVOLVE_NODE_TIER LANGCHAIN_PROJECT
#
# Why this file exists: any `with:` value carrying a ${{ }} expression
# compiles to ONE GitHub expression, hard-capped at 21,000 chars of the
# COMPILED form (quote/brace escaping inflates the raw text — a raw
# measurement of 20,966 was rejected on 2026-08-24, run 32754055050, the
# third collision with this cap). Living in the repo, the script has no
# size limit and one home.
set -e

echo "=== Ensure .env exists ==="
# Create ONLY when absent. An existing .env is the node's live
# configuration and may carry values this workflow does not know,
# so it is never rewritten -- the reset above leaves it alone
# because .env is untracked. On a rebuilt or fresh box there was
# previously nothing to recreate it from, which meant the LLM
# routing existed solely on one machine and would have been lost.
#
# Everything written here is either non-secret or a placeholder.
# HARTOS holds no provider credential in this arrangement: it
# calls a sibling gateway that owns the real Azure key and exposes
# an OpenAI-compatible /v1, so the token below only has to be
# non-empty for the SDK to construct a client.
#
# Values are UNQUOTED deliberately. docker --env-file passes quotes
# through literally, so KEY="value" sends the quote characters as
# part of the value; that produced 401s on every agent call with
# nothing in the logs naming the cause.
LLM_GATEWAY="${LLM_GATEWAY_URL}"
[ -z "$LLM_GATEWAY" ] && LLM_GATEWAY="http://172.17.0.1:5459/v1"

if [ -f .env ]; then
  echo ".env present ($(grep -cE '^[A-Z_]+=' .env) vars) — left untouched"
else
  echo ".env absent — synthesising so this box is reproducible"
  umask 077
  {
    echo "# Generated by deploy-hartos-deepbox.yml (no .env was present)."
    echo "# Values are intentionally unquoted; see the workflow for why."
    echo "OPENAI_API_KEY=hartos-internal-via-gateway"
    echo "OPENAI_MODEL=gpt-4o-mini"
    echo "OPENAI_BASE_URL=$LLM_GATEWAY"
    echo "OPENAI_API_BASE=$LLM_GATEWAY"
    echo "HEVOLVE_LLM_ENDPOINT_URL=$LLM_GATEWAY"
    echo "HEVOLVE_LLM_MODEL_NAME=gpt-4o-mini"
    echo "HEVOLVE_LLM_API_KEY=hartos-internal-via-gateway"
    echo "HEVOLVE_LOCAL_LLM_URL=$LLM_GATEWAY"
    echo "CUSTOM_LLM_BASE_URL=$LLM_GATEWAY"
    echo "HEVOLVE_NODE_TIER=${HEVOLVE_NODE_TIER:-central}"
    echo "HEVOLVE_ENFORCEMENT_MODE=${HEVOLVE_ENFORCEMENT_MODE:-hard}"
    # OTA_HOST is APPENDED, never replaced: /api/ota/latest is the
    # PUBLIC pointer every fleet node polls with
    # `Host: etime.hertzai.com`, and security/middleware.py resolves
    # a NAME against this allowlist (only literal RFC1918 addresses
    # bypass it). The deployed secret is a specific list that omits
    # that name, so every node poll answered 400 {"error":"Invalid
    # host"} and OTA delivery was silently dead fleet-wide -- exactly
    # the failure the middleware's own wildcard comment warns about.
    # Verified on real HW 2026-08-20: same URL, same node,
    # `Host: etime.hertzai.com` -> 400 while `Host: 192.168.0.9`
    # -> 200. Appending keeps whatever the operator set (including
    # '*', which still short-circuits to allow-all) and only ADDS
    # the one host OTA cannot function without.
    echo "ALLOWED_HOSTS=${ALLOWED_HOSTS:-*},${HART_OTA_HOST:-etime.hertzai.com}"
    echo "CORS_ORIGINS=${CORS_ORIGINS:-*}"
    echo "LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-hartos}"
  } > .env
  # Optional integrations. Written only when the secret exists, so
  # a missing one leaves the feature off rather than writing an
  # empty value that looks configured.
  if [ -n "${LANGCHAIN_API_KEY}" ]; then
    echo "LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}" >> .env
  else
    echo "  note: LANGCHAIN_API_KEY secret absent — tracing disabled"
  fi
  if [ -n "${GROQ_API_KEY}" ]; then
    echo "GROQ_API_KEY=${GROQ_API_KEY}" >> .env
  else
    echo "  note: GROQ_API_KEY secret absent — Groq provider unavailable"
  fi
  chmod 600 .env
  echo "  wrote .env with $(grep -cE '^[A-Z_]+=' .env) vars (values not shown)"

  # Fail here rather than after the image build. The env check
  # further down treats these as required, so without them the
  # deploy would spend ten minutes building and then reject the
  # container it just started.
  _absent=""
  for _k in LANGCHAIN_API_KEY GROQ_API_KEY; do
    grep -q "^${_k}=" .env || _absent="$_absent $_k"
  done
  if [ -n "$_absent" ]; then
    echo "::error::synthesised .env is missing required secret(s):$_absent"
    echo "::error::add them under Settings > Secrets and variables > Actions, then re-run"
    exit 1
  fi
fi

# ── The OTA host, guaranteed on EVERY deploy (not just a fresh box) ──
# The block above writes .env only when it is ABSENT, which is the
# right rule (a live .env carries values this workflow does not
# know). The consequence: adding the OTA host to that block fixed
# nothing here. Deepbox's .env is dated 2026-07-21, so the block has
# been skipped on every deploy since, and ALLOWED_HOSTS still read
#   localhost,127.0.0.1,172.17.0.1,azurekong...,hevolve.ai,...
# with no etime.hertzai.com. Verified 2026-08-20 against the LIVE
# container and the file on disk: `Host: 192.168.0.9` -> 200
# {"channel":"stable",...}, `Host: etime.hertzai.com` -> 400
# {"error":"Invalid host"} -- and that name is exactly what every
# fleet node polls (hart-ota.nix defaults to
# http://etime.hertzai.com:6777/api/ota/latest). OTA delivery was
# dead fleet-wide at the first request.
#
# So ensure it separately and idempotently. This does NOT rewrite
# .env: it appends ONE host to ONE key, only when missing, which is
# the same additive contract the create-block comment describes.
# Re-running is a no-op, and an operator's '*' is left alone.
_OTA_HOST="${HART_OTA_HOST:-etime.hertzai.com}"
if [ -n "$_OTA_HOST" ] && [ -f .env ]; then
  if ! grep -q '^ALLOWED_HOSTS=' .env; then
    echo "ALLOWED_HOSTS=$_OTA_HOST" >> .env
    echo "  ALLOWED_HOSTS absent — created it with $_OTA_HOST"
  else
    _CUR="$(grep -E '^ALLOWED_HOSTS=' .env | head -1 | cut -d= -f2-)"
    case ",$_CUR," in
      *",$_OTA_HOST,"*)
        echo "  ALLOWED_HOSTS already allows $_OTA_HOST" ;;
      *"*"*)
        echo "  ALLOWED_HOSTS is allow-all — nothing to add" ;;
      *)
        sed -i "s|^ALLOWED_HOSTS=.*|ALLOWED_HOSTS=$_CUR,$_OTA_HOST|" .env
        echo "  appended $_OTA_HOST to ALLOWED_HOSTS (OTA polls by that name)" ;;
    esac
  fi
fi

DEPLOY_COMMIT="$(git rev-parse HEAD)"
DEPLOY_COMMIT_SHORT="$(git rev-parse --short HEAD)"

echo "Deploy commit: $DEPLOY_COMMIT"
git log -1 --oneline

echo "=== Free disk BEFORE the build ==="
# Deepbox was filling up (dozens of ~8GB langchain_gpt:<sha> + <none>
# images from prior --no-cache builds), so the build itself failed
# with 'No space left on device' at apt-get — which meant the OLD
# end-of-run prune could never execute.  So reclaim FIRST, then build.
#
# The running container is deliberately NOT removed here, though it
# used to be. Killing it first meant :6777 was dead for the whole
# ~18-minute build, and Kong's hartos-social route points straight
# at it, so every /api/social/* call 502'd for the duration --
# including /auth/register, i.e. nobody could sign up. Worse, the
# container was only recreated at the END, so any failed build left
# the box with no HARTOS at all until someone landed a green deploy.
# Three failed builds in one day is how the site sat unable to
# register users. Reclaiming images and build cache frees the disk
# that actually matters; the live container is a few hundred MB and
# is now swapped only once its replacement is built and healthy.
docker rm -f langchain_tmp 2>/dev/null || true
docker rmi -f langchain_gpt:main 2>/dev/null || true   # drop legacy :main (now using :latest)
# Delete every stale langchain_gpt tag except :latest/:main (the
# possible running image).  rmi -f only removes the TAG if the image
# backs a running container, so the live service stays up.
docker images 'langchain_gpt' --format '{{.Repository}}:{{.Tag}}' \
  | grep -vE ":(latest|main)$" \
  | xargs -r docker rmi -f 2>/dev/null || true
docker image prune -f || true      # dangling <none> layers
docker builder prune -af || true   # ALL build cache
echo "--- disk after pre-build prune ---"
docker system df || true
df -h / || true

echo "=== Build Docker image ==="
# Built under the commit tag ONLY. :latest is the rollback target
# and must keep pointing at the last image known to have served
# traffic, so it is moved (further down) after the new container
# answers /status -- not by the build. Tagging :latest here meant a
# broken build silently overwrote the one good image on the box.
docker build --no-cache \
  --build-arg GIT_SHA="$DEPLOY_COMMIT" \
  -t langchain_gpt:"$DEPLOY_COMMIT_SHORT" \
  .

echo "=== Generate signed release manifest ==="
sudo docker run --name langchain_tmp -d \
  --env-file .env \
  -e HEVOLVE_MASTER_PRIVATE_KEY="$(sudo cat ${DEPLOY_MASTER_KEY_PATH})" \
  langchain_gpt:"$DEPLOY_COMMIT_SHORT" sleep 3600

docker exec langchain_tmp sh -lc '
cd /app
export MASTER_PRIVATE_KEY_HEX="$HEVOLVE_MASTER_PRIVATE_KEY"
python scripts/sign_release.py \
  --version "'"$DEPLOY_COMMIT_SHORT"'" \
  --git-sha "'"$DEPLOY_COMMIT"'" \
  --code-hash "$(python - <<PY
import sys; sys.path.insert(0,".")
from security.node_integrity import compute_code_hash
print(compute_code_hash())
PY
)" \
  --manifest-hash "$(python - <<PY
import sys, hashlib, json; sys.path.insert(0,".")
from security.node_integrity import compute_file_manifest
m=compute_file_manifest()
print(hashlib.sha256(json.dumps(m, sort_keys=True).encode()).hexdigest())
PY
)" \
  --output /tmp/release_manifest.json
'

sudo docker cp langchain_tmp:/tmp/release_manifest.json ./release_manifest.json
docker rm -f langchain_tmp

echo "=== Validate release manifest on Deepbox ==="
ls -l release_manifest.json
file release_manifest.json
python3 -m json.tool release_manifest.json >/dev/null
echo "release_manifest.json valid JSON"

echo "=== Manifest fields ==="
python3 - <<'PY'
import json
m = json.load(open("release_manifest.json"))
required = ["version", "git_sha", "code_hash", "guardrail_hash", "master_signature"]
missing = [k for k in required if not m.get(k)]
if missing:
    raise SystemExit("Missing manifest fields: %s" % missing)
for k in required:
    print(k, "=", str(m.get(k))[:120])
PY

echo "=== Channel OAuth credentials (side env-file) ==="
# The "Connect a channel" click-through (Discord, Slack, etc.)
# reads HARTOS_OAUTH_CLIENT_<TYPE> / HARTOS_OAUTH_SECRET_<TYPE>.
# These cannot ride in the synthesised .env block above, because
# that block only runs when .env is ABSENT and on this box .env
# already exists and is deliberately left untouched. So they go in
# a separate file passed as a second --env-file, regenerated from
# one secret every deploy.
#
# ONE multi-line secret HARTOS_OAUTH_ENV holds the KEY=VALUE lines
# (HARTOS_OAUTH_CLIENT_DISCORD=..., HARTOS_OAUTH_SECRET_DISCORD=...,
# one per line) so the owner can enable ANY of the nine OAuth
# channels by editing one secret, without this workflow changing
# again. When the secret is unset the file is empty, no channel is
# configured, and the connect UI shows the layman "not switched on
# yet" message (6fad2576) instead of failing. Registering the
# provider app itself stays an owner action; this only carries the
# result so it survives redeploys.
umask 077
_oauth_n="$(grep -cE '^HARTOS_OAUTH_(CLIENT|SECRET)_' oauth.env || true)"
echo "  oauth.env: $_oauth_n credential line(s) present"

echo "=== Run central container ==="
# Remember what was serving so a bad release can be put back. This
# is the last moment :6777 goes away, and the new container is
# started immediately after, so the outage window is a container
# restart rather than a full image build.
ROLLBACK_IMAGE="$(docker inspect langchain --format '{{.Config.Image}}' 2>/dev/null || true)"
[ -z "$ROLLBACK_IMAGE" ] && ROLLBACK_IMAGE="langchain_gpt:latest"
echo "rollback target: $ROLLBACK_IMAGE"
docker rm -f langchain 2>/dev/null || true

# Routable self-URL; a bridge NIC leaks otherwise (172.17.0.4, 2026-08-24).
ADVERTISE_URL="${DEPLOY_ADVERTISE_URL}"
if [ -z "$ADVERTISE_URL" ]; then
  _HOST_IP="$(ip route get 1 2>/dev/null | awk '{for(i=1;i<NF;i++) if ($i=="src") {print $(i+1); exit}}')"
  [ -n "$_HOST_IP" ] && ADVERTISE_URL="http://${_HOST_IP}:6777"
fi
echo "advertise URL: ${ADVERTISE_URL:-unset}"
ADV_ARGS=""
[ -n "$ADVERTISE_URL" ] && ADV_ARGS="-e HEVOLVE_BASE_URL=$ADVERTISE_URL"
# Flywheel state (goals DB, prospects, node keys) must survive rebuilds.
AD="${DEPLOY_AGENT_DATA_PATH}"; [ -z "$AD" ] && AD=/opt/hzai-LLM-Langchain-Chatbot-Agent/agent_data; sudo mkdir -p "$AD"

sudo docker run -d --name langchain --restart unless-stopped \
  -p 6777:6777 \
  --env-file .env \
  --env-file oauth.env \
  $ADV_ARGS \
  -e HEVOLVE_MASTER_PRIVATE_KEY="$(sudo cat ${DEPLOY_MASTER_KEY_PATH})" \
  -e HARTOS_GIT_SHA="$DEPLOY_COMMIT" \
  -e HARTOS_IMAGE_TAG="$DEPLOY_COMMIT_SHORT" \
  -e WHATSAPP_API_URL="http://172.17.0.1:3000" \
  -v "$(pwd)/config.json:/app/config.json:ro" \
  -v "$(pwd)/release_manifest.json:/app/release_manifest.json:ro" \
  -v ${DEPLOY_LOGS_PATH}:/app/logs \
  -v ${DEPLOY_IMAGES_PATH}:/app/output_images \
  -v "$AD":/app/agent_data \
  -e HEVOLVE_KEY_DIR=/app/agent_data \
  -e HEVOLVE_AGENT_DATA=/app/agent_data \
  langchain_gpt:"$DEPLOY_COMMIT_SHORT"

echo "=== Wait for service ==="
sleep 20

echo "=== Verify container is running ==="
docker ps | grep langchain
docker inspect langchain --format 'Image={{.Config.Image}} ContainerID={{.Id}} RestartCount={{.RestartCount}}'

echo "=== Verify env inside container ==="
docker exec langchain sh -lc '
python - <<PY
import os
keys = [
    "OPENAI_API_KEY",
    "LANGCHAIN_API_KEY",
    "GROQ_API_KEY",
    "HEVOLVE_NODE_TIER",
    "HEVOLVE_ENFORCEMENT_MODE",
    "ALLOWED_HOSTS",
    "HARTOS_GIT_SHA",
    "HARTOS_IMAGE_TAG",
]
missing = []
for k in keys:
    v = os.getenv(k)
    print(k, "=", "set" if v else "missing")
    if not v:
        missing.append(k)
if missing:
    raise SystemExit("Missing env vars: " + ",".join(missing))

# Values arriving through docker --env-file keep any quotes the
# file wrote. OPENAI_API_KEY was stored as "sk-..." and every
# request went out with literal quote characters around the key,
# so the LLM answered 401 and every agent goal produced nothing
# while still reporting as dispatched. Catch it at deploy time.
for k in ("OPENAI_API_KEY", "AZURE_OPENAI_API_KEY", "GROQ_API_KEY",
          "LANGCHAIN_API_KEY", "AZURE_OPENAI_ENDPOINT"):
    v = os.getenv(k) or ""
    if v[:1] in ("\"", "'"'"'") or v[-1:] in ("\"", "'"'"'"):
        raise SystemExit(
            k + " is quote-wrapped in the env file; docker passes "
            "the quotes through and the credential will be rejected")

# Azure is optional, but half-configured Azure is not: the client
# silently falls back to api.openai.com, which is how this node
# ended up calling a public endpoint with a dead key.
az = [k for k in ("AZURE_OPENAI_ENDPOINT", "AZURE_OPENAI_API_KEY",
                  "AZURE_OPENAI_DEPLOYMENT") if os.getenv(k)]
if az and len(az) < 3:
    raise SystemExit("partial Azure config: " + ",".join(az))
print("azure openai:", "configured" if len(az) == 3 else "not used")

# Three independent consumers each read a DIFFERENT variable for
# the LLM endpoint. Setting only some of them produces a node that
# deploys green and half-works: recipes reach the endpoint while
# /chat quietly falls back to a local llama.cpp that is not
# running, with no error naming the cause. That exact split cost a
# night of debugging, so a partially-routed node now fails here
# rather than in production.
routes = {
    "HEVOLVE_LLM_ENDPOINT_URL": "autogen / recipes",
    "OPENAI_BASE_URL": "langchain ChatOpenAI",
    "HEVOLVE_LOCAL_LLM_URL": "port_registry.get_local_llm_url",
}
have = {k: os.getenv(k) for k in routes if os.getenv(k)}
if have and len(have) < len(routes):
    missing = [f"{k} ({routes[k]})" for k in routes if k not in have]
    raise SystemExit(
        "LLM endpoint only partially routed; these consumers would "
        "fall back elsewhere: " + "; ".join(missing))
if have:
    # Differing values are legitimate (deliberately splitting
    # subsystems across models) but rare enough to be worth saying
    # out loud in the deploy log.
    distinct = set(have.values())
    print("llm routing:", "all consumers ->", distinct.pop()
          if len(distinct) == 1 else f"SPLIT across {len(distinct)} endpoints")
else:
    print("llm routing: none set (provider defaults apply)")
PY
'

echo "=== Status check ==="
# Poll until ready instead of trusting the fixed sleep above.
# HARTOS boots a large app (heavy imports, then synchronous
# agent-engine blueprint registration before it serves), so a
# single curl after 20s raced the boot and reported
# "Recv failure: Connection reset by peer" on a deploy that had
# actually succeeded. A false failure is worse than a slow one:
# it hides the real ones.
STATUS_JSON=""
for _i in $(seq 1 60); do
  if STATUS_JSON="$(curl -fsS --max-time 10 http://127.0.0.1:6777/status 2>/dev/null)"; then
    echo "status endpoint responded after $(( _i * 5 ))s"
    break
  fi
  STATUS_JSON=""
  sleep 5
done
if [ -z "$STATUS_JSON" ]; then
  echo "::error::status endpoint never came up (300s) -- rolling back"
  docker logs --tail 80 langchain 2>&1 || true
  # Put the previous release back rather than leaving :6777 dead.
  # Kong routes /api/social/* here, so an empty box is a site-wide
  # signup outage; a slightly stale HARTOS is strictly better.
  docker rm -f langchain 2>/dev/null || true
  if sudo docker run -d --name langchain --restart unless-stopped \
       -p 6777:6777 \
       --env-file .env \
       --env-file oauth.env \
       $ADV_ARGS \
       -e HEVOLVE_MASTER_PRIVATE_KEY="$(sudo cat ${DEPLOY_MASTER_KEY_PATH})" \
       -e WHATSAPP_API_URL="http://172.17.0.1:3000" \
       -v "$(pwd)/config.json:/app/config.json:ro" \
       -v ${DEPLOY_LOGS_PATH}:/app/logs \
       -v ${DEPLOY_IMAGES_PATH}:/app/output_images \
       -v "$AD":/app/agent_data \
       -e HEVOLVE_KEY_DIR=/app/agent_data \
       -e HEVOLVE_AGENT_DATA=/app/agent_data \
       "$ROLLBACK_IMAGE"; then
    echo "rolled back to $ROLLBACK_IMAGE"
  else
    echo "::error::rollback to $ROLLBACK_IMAGE also failed -- :6777 is DOWN"
  fi
  exit 1
fi
echo "$STATUS_JSON"

echo "$STATUS_JSON" | python3 -c 'import sys,json; data=json.load(sys.stdin); assert data.get("status")=="running"; assert data.get("node_tier")=="central"; print("status endpoint OK")'


echo "=== Compare manifest commit with deployed commit ==="
python3 - <<PY
import json

deploy_commit = "$DEPLOY_COMMIT"

with open("release_manifest.json") as f:
    manifest = json.load(f)

manifest_commit = manifest.get("git_sha") or manifest.get("commit") or manifest.get("version")

if manifest_commit != deploy_commit:
    raise SystemExit(
        "Manifest commit mismatch: manifest=%s, deployed=%s" % (manifest_commit, deploy_commit)
    )

print("Manifest commit matches deployed commit:", deploy_commit)
PY

echo "=== Promote this image to :latest ==="
# Only now, with the container up and /status answering, does
# :latest move. That keeps :latest meaning "last image known to
# have actually served traffic", which is what makes it a safe
# rollback target on the next deploy.
docker tag langchain_gpt:"$DEPLOY_COMMIT_SHORT" langchain_gpt:latest
echo "langchain_gpt:latest -> $DEPLOY_COMMIT_SHORT"

echo "=== Final verification complete ==="
echo "HARTOS central deployment verified for commit $DEPLOY_COMMIT"

echo "=== Prune old images (stop the Deepbox disk bloat) ==="
# The new container (langchain_gpt:latest) is up + verified above, so it
# is now safe to reclaim what this workflow used to leave behind on
# every deploy (each langchain_gpt image is ~8GB; they were never
# removed, which filled Deepbox with 8.33GB tagged + <none> images):
#   1) every stale langchain_gpt tag — keep ONLY :latest and the
#      short-sha we just deployed.  This deletes the old commit-id
#      tags (a3de3484, 716fe33b, ...) and the legacy :main, reclaiming
#      ~8GB each; the running image (:latest) is untouched.
docker images 'langchain_gpt' --format '{{.Repository}}:{{.Tag}}' \
  | grep -vE ":(latest|${DEPLOY_COMMIT_SHORT})$" \
  | xargs -r docker rmi -f 2>/dev/null || true
#   2) dangling <none> layers left by the --no-cache rebuild.
#      prune only removes images not used by any container, so the
#      running langchain_gpt:latest is safe.
docker image prune -f || true
#   3) build cache.
docker builder prune -f || true
echo "=== Disk after prune ==="
docker system df || true
