"""The serialised tool schema must carry information, not pydantic boilerplate.

THE DEFECT, measured 2026-09-11 on the real wire body that killed agent
18163818525 (llm_outbound.jsonl, ts 22:34:31, source autogen.reuse, 70 tools)::

    [TRIM] trim could not reach budget - request is STILL over and will very
    likely be rejected: messages 1868 tok + schema 8482 tok = 10350 tok
    against n_ctx 8192

Messages were already trimmed to their floor, so the schema alone decided the
turn.  Anatomy of those 8,482 tokens, measured per tool:

    parameters   5090 tok  (60.0%)      <- the JSON Schema blocks
    JSON overhead 1623 tok  (19.1%)
    descriptions  1519 tok  (17.9%)
    names          250 tok  ( 2.9%)

So the fat is NOT the prose - deleting every description outright would
recover 18% and break tool selection.  It is the ``parameters`` blocks, and
inside them it is boilerplate that pydantic emits for ``Optional[X] = None``::

    "repo": {"anyOf": [{"type": "string"}, {"type": "null"}],
             "default": null, "description": "repo"}

Three separate wastes in one property, all recoverable with ZERO capability
change:

  1. ``anyOf: [{type: X}, {type: null}]`` - optionality is ALREADY carried by
     the property's absence from ``required``.  The null branch also widens
     llama.cpp's GBNF grammar for no gain.
  2. ``"default": null`` - redundant with not-required, and llama-server does
     not act on defaults.
  3. ``"description": "repo"`` - a description that merely repeats its own key
     is zero information.  These are an artefact of #542's signature
     synthesis, which fills a description from the parameter name when the
     source function had no per-arg docstring.

Measured recovery on that exact 70-tool block:

    collapse anyOf-null wrapper      -427 tok  (38 properties)
    drop redundant default:null      -185 tok  (37 properties)
    drop name-echo descriptions      -237 tok  (36 properties)
    ALL THREE                        -842 tok  ->  8482 = 7640

HONEST SCOPE - READ BEFORE CITING THIS FILE.  842 tokens does NOT by itself
make the 70-tool body fit: 7640 + 1868 = 9508, still over an n_ctx of 8192.
This guard pins the lossless half of the fix.  Bounding the tool COUNT is a
separate change with a separate guard; do not read a green run here as "the
oversized body now fits".

WHY THE WIRE LAYER.  The schema is generated by autogen/pydantic from Python
signatures inside third-party code, so there is no producer-side seam to fix.
The wire is the one place every framework's body converges (autogen, langchain,
raw openai SDK all funnel through httpx here) and it is already where
``_schema_tokens`` charges the schema - so the compaction and the budget
arithmetic are the same number by construction, which is what stops them
drifting apart.

RED BEFORE GREEN: ``_compact_tool_schema`` does not exist at HEAD, so every
test below fails at import/attribute lookup.

    python -m pytest tests/unit/test_wire_compacts_the_tool_schema.py --noconftest -q
"""
import copy
import importlib
import json

import pytest

MOD = 'core.llm_outbound_logger'


@pytest.fixture
def wire():
    return importlib.import_module(MOD)


def _tool(name, properties, required=()):
    return {'type': 'function',
            'function': {'name': name,
                         'description': f'does {name}',
                         'parameters': {'type': 'object',
                                        'properties': properties,
                                        'required': list(required)}}}


def _optional_str(desc):
    """Exactly what pydantic emits for ``Optional[str] = None``."""
    return {'anyOf': [{'type': 'string'}, {'type': 'null'}],
            'default': None, 'description': desc}


def test_optional_wrapper_collapses_to_the_plain_type(wire):
    """``anyOf:[{type:X},{type:null}]`` -> ``{type:X}`` for a non-required arg.

    The null branch is redundant with the property being absent from
    ``required``, and it is the single largest line item (427 tok / 38 sites
    on the measured body).
    """
    body = {'tools': [_tool('gh_pr_open', {'repo': _optional_str('repo')})]}
    out, saved = wire._compact_tool_schema(body)
    spec = out['tools'][0]['function']['parameters']['properties']['repo']
    assert spec.get('type') == 'string', (
        'the non-null branch must survive as a plain type, got %r' % (spec,))
    assert 'anyOf' not in spec
    assert saved > 0


def test_a_required_argument_keeps_its_union(wire):
    """Only NON-required properties may lose the null branch.

    When a property IS required the caller must pass something, and null may
    be the something.  Collapsing there would change the contract rather than
    normalise its serialisation.
    """
    body = {'tools': [_tool('t', {'x': _optional_str('x')}, required=['x'])]}
    out, _ = wire._compact_tool_schema(body)
    spec = out['tools'][0]['function']['parameters']['properties']['x']
    assert 'anyOf' in spec, (
        'a REQUIRED property still has to admit null explicitly; collapsing '
        'it silently narrows the tool contract')


def test_redundant_null_default_is_dropped_but_a_real_default_is_kept(wire):
    """``default: null`` says nothing; ``default: "hybrid"`` says a lot.

    recall_memory's ``mode`` carries ``default: 'hybrid'`` and that genuinely
    steers the model.  A blanket "drop all defaults" would have cost that.
    """
    body = {'tools': [_tool('recall_memory', {
        'since': _optional_str('since'),
        'mode': {'type': 'string', 'default': 'hybrid',
                 'description': "Search mode: 'hybrid', 'semantic', 'text'."},
    })]}
    out, _ = wire._compact_tool_schema(body)
    props = out['tools'][0]['function']['parameters']['properties']
    assert 'default' not in props['since']
    assert props['mode']['default'] == 'hybrid', (
        'an informative default must survive - it is the only thing telling '
        'the model what happens when it omits the argument')


def test_name_echo_description_is_dropped_but_a_real_one_is_kept(wire):
    """A description equal to its own key carries no information."""
    body = {'tools': [_tool('t', {
        'head_branch': _optional_str('head_branch'),
        'query': {'type': 'string',
                  'description': 'What to look for, in natural language.'},
    })]}
    out, _ = wire._compact_tool_schema(body)
    props = out['tools'][0]['function']['parameters']['properties']
    assert 'description' not in props['head_branch']
    assert props['query']['description'].startswith('What to look for'), (
        'a real per-argument description is how the model fills the argument '
        'correctly - #787 measured 53% of calls emitted with empty arguments')


def test_nothing_is_lost_that_the_model_needs(wire):
    """Every tool, every property and every required arg survives intact.

    This is the whole claim of "lossless": the compaction may only change how
    the schema is SPELLED, never which tools exist, which arguments they take,
    or which of those are mandatory.
    """
    tools = [
        _tool('gh_pr_open', {'repo': _optional_str('repo'),
                             'title': _optional_str('title'),
                             'draft': {'anyOf': [{'type': 'boolean'},
                                                 {'type': 'null'}],
                                       'default': None,
                                       'description': 'draft'}},
              required=[]),
        _tool('recall_memory', {'query': {'type': 'string',
                                          'description': 'what to find'},
                                'since': _optional_str('since')},
              required=['query']),
        _tool('get_user_id', {}),
    ]
    before = copy.deepcopy(tools)
    out, saved = wire._compact_tool_schema({'tools': tools})

    def shape(block):
        return {f['function']['name']: (
            sorted((f['function'].get('parameters') or {}).get(
                'properties', {})),
            sorted((f['function'].get('parameters') or {}).get('required', [])))
            for f in block}

    assert shape(out['tools']) == shape(before)
    assert saved > 0
    assert tools == before, (
        'the input block was mutated in place - autogen reuses its llm_config '
        'across turns, so an in-place edit would compound every call')


def test_it_is_idempotent(wire):
    """A second pass must be a strict no-op reporting zero saving.

    The wire trim runs on every outbound body and ``_apply_trim_to_request``
    keys "did anything change" off identity, so a compaction that kept
    reporting a saving would force a needless re-serialisation forever.
    """
    body = {'tools': [_tool('t', {'a': _optional_str('a')})]}
    once, saved1 = wire._compact_tool_schema(body)
    twice, saved2 = wire._compact_tool_schema(once)
    assert saved1 > 0
    assert saved2 == 0
    assert twice['tools'] == once['tools']


def test_a_body_with_no_tools_is_untouched(wire):
    """The 69% of bodies carrying no tools must not pay for this."""
    body = {'messages': [{'role': 'user', 'content': 'hi'}]}
    out, saved = wire._compact_tool_schema(body)
    assert out is body and saved == 0


def test_malformed_schema_never_raises(wire):
    """A logging/trim hook may never fail an LLM call.

    Real bodies have carried non-dict tool entries and string parameters;
    the compaction must skip what it does not understand rather than throw on
    the chat hot path.
    """
    body = {'tools': [None, 'nonsense', {'function': None},
                      {'function': {'name': 'x', 'parameters': 'not-a-dict'}},
                      {'function': {'name': 'y', 'parameters':
                                    {'properties': {'a': 'not-a-dict'}}}}]}
    out, saved = wire._compact_tool_schema(body)
    assert saved == 0
    assert json.dumps(out)  # still serialisable


def test_the_budget_sees_the_compacted_schema(wire, monkeypatch):
    """``_trim_to_budget`` must charge what actually goes on the wire.

    If the compaction happened after ``_schema_tokens`` was computed, the
    budget would be pessimistic by exactly the saving and the degrade branch
    would still fire - the drift this layer exists to prevent.
    """
    monkeypatch.setattr(wire, '_get_budget_per_slot', lambda: 8192)
    tools = [_tool(f't{i}', {f'p{j}': _optional_str(f'p{j}')
                             for j in range(6)}) for i in range(40)]
    body = {'model': 'qwen', 'max_tokens': 512,
            'messages': [{'role': 'user', 'content': 'go'}],
            'tools': tools}
    fat = wire._schema_tokens(body, None)
    out = wire._trim_to_budget(copy.deepcopy(body))[0]
    lean = wire._schema_tokens(out, None)
    assert lean < fat, (
        'the body returned by _trim_to_budget still carries the uncompacted '
        'schema (%d tok) - the wire pays the full cost' % lean)
