"""The environment names a vault value may be delivered to: generated, not
edited by hand.

hartos.ai_key_vault.reads_from_env reads DELIVERABLE, so the first call, on
Nunba's boot path (desktop ai_key_vault.export_to_env), imports no channel
adapter; collecting by import took about 6 s there.  collect() builds the
same set from the declarations (SECRET_KEYS without the node secrets, every
channel's FlaskChannelIntegration.env_names(), each
ai_key_vault._ENV_SECRET_MODULES module's ENV_SECRETS).
tests/unit/test_env_secrets_declared.py fails when DELIVERABLE != collect().

Regenerate:  python -m hartos.env_secrets_manifest
"""
import os

#: GENERATED by python -m hartos.env_secrets_manifest
DELIVERABLE = frozenset({
    'ANTHROPIC_API_KEY',
    'BLUEBUBBLES_APP_SECRET',
    'BLUEBUBBLES_CHANNEL_SECRET',
    'BLUEBUBBLES_PASSWORD',
    'BLUEBUBBLES_SERVER_URL',
    'BLUEBUBBLES_VERIFY_TOKEN',
    'BLUEBUBBLES_WEBHOOK_SECRET',
    'COMMERCE_SESSION_SECRET',
    'DISCORD_APP_SECRET',
    'DISCORD_BOT_TOKEN',
    'DISCORD_CHANNEL_SECRET',
    'DISCORD_USER_APP_SECRET',
    'DISCORD_USER_CHANNEL_SECRET',
    'DISCORD_USER_TOKEN',
    'DISCORD_USER_VERIFY_TOKEN',
    'DISCORD_USER_WEBHOOK_SECRET',
    'DISCORD_VERIFY_TOKEN',
    'DISCORD_WEBHOOK_SECRET',
    'EMAIL_APP_SECRET',
    'EMAIL_CHANNEL_SECRET',
    'EMAIL_PASSWORD',
    'EMAIL_VERIFY_TOKEN',
    'EMAIL_WEBHOOK_SECRET',
    'ERXES_PASSWORD',
    'GH_TOKEN',
    'GITHUB_TOKEN',
    'GOOGLE_API_KEY',
    'GOOGLE_CALENDAR_TOKEN',
    'GOOGLE_CHAT_APP_SECRET',
    'GOOGLE_CHAT_CHANNEL_SECRET',
    'GOOGLE_CHAT_SA_FILE',
    'GOOGLE_CHAT_VERIFY_TOKEN',
    'GOOGLE_CHAT_WEBHOOK',
    'GOOGLE_CHAT_WEBHOOK_SECRET',
    'GOOGLE_CSE_ID',
    'GROQ_API_KEY',
    'HARTOS_OAUTH_CLIENT_DISCORD',
    'HARTOS_OAUTH_CLIENT_GOOGLE_CHAT',
    'HARTOS_OAUTH_CLIENT_INSTAGRAM',
    'HARTOS_OAUTH_CLIENT_LINE',
    'HARTOS_OAUTH_CLIENT_MESSENGER',
    'HARTOS_OAUTH_CLIENT_SLACK',
    'HARTOS_OAUTH_CLIENT_TEAMS',
    'HARTOS_OAUTH_CLIENT_TWITCH',
    'HARTOS_OAUTH_CLIENT_TWITTER',
    'HARTOS_OAUTH_SECRET_DISCORD',
    'HARTOS_OAUTH_SECRET_GOOGLE_CHAT',
    'HARTOS_OAUTH_SECRET_INSTAGRAM',
    'HARTOS_OAUTH_SECRET_LINE',
    'HARTOS_OAUTH_SECRET_MESSENGER',
    'HARTOS_OAUTH_SECRET_SLACK',
    'HARTOS_OAUTH_SECRET_TEAMS',
    'HARTOS_OAUTH_SECRET_TWITCH',
    'HARTOS_OAUTH_SECRET_TWITTER',
    'HEVOLVE_API_KEY',
    'HEVOLVE_GITHUB_TOKEN',
    'HEVOLVE_HF_TOKEN',
    'IMESSAGE_APP_SECRET',
    'IMESSAGE_CHANNEL_SECRET',
    'IMESSAGE_VERIFY_TOKEN',
    'IMESSAGE_WEBHOOK_SECRET',
    'INSTAGRAM_APP_SECRET',
    'INSTAGRAM_CHANNEL_SECRET',
    'INSTAGRAM_PAGE_TOKEN',
    'INSTAGRAM_VERIFY_TOKEN',
    'INSTAGRAM_WEBHOOK_SECRET',
    'LANGCHAIN_API_KEY',
    'LINE_APP_SECRET',
    'LINE_CHANNEL_ACCESS_TOKEN',
    'LINE_CHANNEL_SECRET',
    'LINE_VERIFY_TOKEN',
    'LINE_WEBHOOK_SECRET',
    'LIVEKIT_API_KEY',
    'LIVEKIT_API_SECRET',
    'MATRIX_ACCESS_TOKEN',
    'MATRIX_APP_SECRET',
    'MATRIX_CHANNEL_SECRET',
    'MATRIX_HOMESERVER_URL',
    'MATRIX_USER_ID',
    'MATRIX_VERIFY_TOKEN',
    'MATRIX_WEBHOOK_SECRET',
    'MATTERMOST_APP_SECRET',
    'MATTERMOST_CHANNEL_SECRET',
    'MATTERMOST_SERVER_URL',
    'MATTERMOST_TOKEN',
    'MATTERMOST_VERIFY_TOKEN',
    'MATTERMOST_WEBHOOK_SECRET',
    'MCGROCE_ADMIN_API_KEY',
    'MCGROCE_API_PASSWORD',
    'MESSENGER_APP_SECRET',
    'MESSENGER_CHANNEL_SECRET',
    'MESSENGER_PAGE_TOKEN',
    'MESSENGER_VERIFY_TOKEN',
    'MESSENGER_WEBHOOK_SECRET',
    'NEWS_API_KEY',
    'NEXTCLOUD_APP_PASSWORD',
    'NEXTCLOUD_APP_SECRET',
    'NEXTCLOUD_CHANNEL_SECRET',
    'NEXTCLOUD_URL',
    'NEXTCLOUD_USERNAME',
    'NEXTCLOUD_VERIFY_TOKEN',
    'NEXTCLOUD_WEBHOOK_SECRET',
    'NOSTR_APP_SECRET',
    'NOSTR_CHANNEL_SECRET',
    'NOSTR_PRIVATE_KEY',
    'NOSTR_VERIFY_TOKEN',
    'NOSTR_WEBHOOK_SECRET',
    'OPENAI_API_KEY',
    'OPENPROSE_API_KEY',
    'OPENPROSE_APP_SECRET',
    'OPENPROSE_CHANNEL_SECRET',
    'OPENPROSE_VERIFY_TOKEN',
    'OPENPROSE_WEBHOOK_SECRET',
    'PHONEPE_SALT_KEY',
    'ROCKETCHAT_APP_SECRET',
    'ROCKETCHAT_AUTH_TOKEN',
    'ROCKETCHAT_CHANNEL_SECRET',
    'ROCKETCHAT_PASSWORD',
    'ROCKETCHAT_URL',
    'ROCKETCHAT_USER_ID',
    'ROCKETCHAT_VERIFY_TOKEN',
    'ROCKETCHAT_WEBHOOK_SECRET',
    'SERPAPI_API_KEY',
    'SIGNAL_API_URL',
    'SIGNAL_APP_SECRET',
    'SIGNAL_CHANNEL_SECRET',
    'SIGNAL_PHONE_NUMBER',
    'SIGNAL_VERIFY_TOKEN',
    'SIGNAL_WEBHOOK_SECRET',
    'SIMPLEMEM_API_KEY',
    'SLACK_APP_SECRET',
    'SLACK_APP_TOKEN',
    'SLACK_BOT_TOKEN',
    'SLACK_CHANNEL_SECRET',
    'SLACK_VERIFY_TOKEN',
    'SLACK_WEBHOOK_SECRET',
    'STRIPE_API_KEY',
    'TEAMS_APP_PASSWORD',
    'TEAMS_APP_SECRET',
    'TEAMS_BOT_TOKEN',
    'TEAMS_CHANNEL_SECRET',
    'TEAMS_VERIFY_TOKEN',
    'TEAMS_WEBHOOK_SECRET',
    'TELEGRAM_API_HASH',
    'TELEGRAM_APP_SECRET',
    'TELEGRAM_BOT_TOKEN',
    'TELEGRAM_CHANNEL_SECRET',
    'TELEGRAM_USER_APP_SECRET',
    'TELEGRAM_USER_CHANNEL_SECRET',
    'TELEGRAM_USER_VERIFY_TOKEN',
    'TELEGRAM_USER_WEBHOOK_SECRET',
    'TELEGRAM_VERIFY_TOKEN',
    'TELEGRAM_WEBHOOK_SECRET',
    'TLON_APP_SECRET',
    'TLON_CHANNEL_SECRET',
    'TLON_VERIFY_TOKEN',
    'TLON_WEBHOOK_SECRET',
    'TWILIO_AUTH_TOKEN',
    'TWITCH_ACCESS_TOKEN',
    'TWITCH_APP_SECRET',
    'TWITCH_BOT_USERNAME',
    'TWITCH_CHANNEL_SECRET',
    'TWITCH_CLIENT_SECRET',
    'TWITCH_VERIFY_TOKEN',
    'TWITCH_WEBHOOK_SECRET',
    'TWITTER_ACCESS_TOKEN',
    'TWITTER_ACCESS_TOKEN_SECRET',
    'TWITTER_APP_SECRET',
    'TWITTER_CHANNEL_SECRET',
    'TWITTER_CONSUMER_KEY',
    'TWITTER_CONSUMER_SECRET',
    'TWITTER_VERIFY_TOKEN',
    'TWITTER_WEBHOOK_SECRET',
    'URBIT_CODE',
    'URBIT_SHIP',
    'URBIT_URL',
    'VIBER_APP_SECRET',
    'VIBER_AUTH_TOKEN',
    'VIBER_BOT_NAME',
    'VIBER_CHANNEL_SECRET',
    'VIBER_VERIFY_TOKEN',
    'VIBER_WEBHOOK_SECRET',
    'VOICE_APP_SECRET',
    'VOICE_CHANNEL_SECRET',
    'VOICE_VERIFY_TOKEN',
    'VOICE_WEBHOOK_SECRET',
    'VONAGE_API_KEY',
    'VONAGE_API_SECRET',
    'WEBHOOK_VERIFY_TOKEN',
    'WEB_APP_SECRET',
    'WEB_CHANNEL_SECRET',
    'WEB_VERIFY_TOKEN',
    'WEB_WEBHOOK_SECRET',
    'WECHAT_APP_ID',
    'WECHAT_APP_SECRET',
    'WECHAT_CHANNEL_SECRET',
    'WECHAT_TOKEN',
    'WECHAT_VERIFY_TOKEN',
    'WECHAT_WEBHOOK_SECRET',
    'WHATSAPP_ACCESS_TOKEN',
    'WHATSAPP_API_KEY',
    'WHATSAPP_API_URL',
    'WHATSAPP_APP_SECRET',
    'WHATSAPP_CHANNEL_SECRET',
    'WHATSAPP_VERIFY_TOKEN',
    'WHATSAPP_WEBHOOK_SECRET',
    'ZALO_ACCESS_TOKEN',
    'ZALO_APP_ID',
    'ZALO_APP_SECRET',
    'ZALO_CHANNEL_SECRET',
    'ZALO_OA_ID',
    'ZALO_PASSWORD',
    'ZALO_USER_APP_SECRET',
    'ZALO_USER_CHANNEL_SECRET',
    'ZALO_USER_VERIFY_TOKEN',
    'ZALO_USER_WEBHOOK_SECRET',
    'ZALO_VERIFY_TOKEN',
    'ZALO_WEBHOOK_SECRET',
    'ZEP_API_KEY',
    'ZOOM_ACCESS_TOKEN',
})


#: security.secrets_manager.NODE_SECRET_KEYS, copied here so is_node_secret
#: needs no import of the security package (1 to 2 s on Nunba's boot).
#: GENERATED as well; the test checks it equals the source.
NODE_SECRETS = frozenset({
    'DATABASE_URL',
    'REDIS_URL',
    'SOCIAL_DB_KEY',
    'SOCIAL_SECRET_KEY',
})


def collect_node() -> frozenset:
    """The node secrets, from their source (security.secrets_manager)."""
    from security.secrets_manager import NODE_SECRET_KEYS
    return frozenset(NODE_SECRET_KEYS)


def collect() -> frozenset:
    """The deliverable names, by importing every declaring module."""
    import importlib
    from security.secrets_manager import NODE_SECRET_KEYS, SECRET_KEYS
    from integrations.channels.flask_integration import FlaskChannelIntegration
    from hartos.ai_key_vault import _ENV_SECRET_MODULES
    names = set(SECRET_KEYS)
    names.update(FlaskChannelIntegration.env_names())
    for module in _ENV_SECRET_MODULES:
        names.update(getattr(importlib.import_module(module), 'ENV_SECRETS', ()))
    return frozenset(names - set(NODE_SECRET_KEYS))


def render(names, text, const='DELIVERABLE') -> str:
    """``text`` (this file) with ``const`` set to ``names``."""
    head, rest = text.split(const + ' = frozenset({\n', 1)
    tail = rest.split('})\n', 1)[1]
    body = ''.join(f"    '{n}',\n" for n in sorted(names))
    return head + const + ' = frozenset({\n' + body + '})\n' + tail


if __name__ == '__main__':
    with open(__file__, encoding='utf-8') as fh:
        current = fh.read()
    names = collect()
    updated = render(collect_node(), render(names, current), 'NODE_SECRETS')
    with open(__file__, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(updated)
    print('wrote', os.path.relpath(__file__), len(names), 'names')
